### ISSUE TITLE
ImportError: No module named apiclient.discovery

### ISSUE THREAD

**Issue by SanskritFritz** [tokland/youtube-upload#1]
I'm trying to run this:
```youtube-upload --email=user@gmail.com --password=pwd --unlisted --category="Autos" --keywords="keyword" --title="title" --description="desc" "movie.avi"```

This is the error I get:
```
Traceback (most recent call last):
  File "/usr/bin/youtube-upload", line 21, in <module>
    import youtube_upload.auth
  File "/usr/lib/python2.7/site-packages/youtube_upload/auth.py", line 4, in <module>
    import apiclient.discovery
ImportError: No module named apiclient.discovery
```

0.7.3 Works well with the same command.

**Comment by SanskritFritz** [comment]
Ok, my fault, no correct dependency was installed, and wrong parameters were given. So, no backwards compatibility :)

**Comment by tokland** [comment]
I had to change so many things that yes, I decided no backwards compatibility :)
