### ISSUE TITLE
Upload stops and the error is not shown

### ISSUE THREAD

**Issue by DavidVentura** [tokland/youtube-upload#106]
Hi
Since I changed ISPs my uploads randomly "error out" and abort. usually within 3 tries it finishes, this is pretty bad and I'm pretty sure my isp is having micro-stuttering or dropouts.

Thing is, I don't get the error because the progressbar prints over it.

```
Using client secrets: /usr/local/share/youtube_upload/client_secrets.json
Using credentials file: /home/user/.youtube-upload-credentials.json
Start upload: FILE
[RequestError] Server response was: ##########################         
```
```
Using client secrets: /usr/local/share/youtube_upload/client_secrets.json
Using credentials file: /home/user/.youtube-upload-credentials.json
Start upload: FILE
[RequestError] Server response was: #####################################################################################################################################################                                                           | ETA:  0:06:40 337.27 kB/s
```

Any way to display this ? Maybe redirect stderr to a file? I'll try that for now

**Comment by tokland** [comment]
Try with chunksize=-1 (modify the code directly)

**Comment by tokland** [comment]
No feedback, closing

**Comment by DavidVentura** [comment]
Either reinstalling progressbar2 fixed the issue or my connection stopped
having issues. If this keeps happening I'll try this and update here.

On 2 May 2016 at 07:04, Arnau Sanchez <notifications@github.com> wrote:

> Closed #106 <https://github.com/tokland/youtube-upload/issues/106>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tokland/youtube-upload/issues/106#event-647412422>
>



-- 
*Stack* is the new term for "I have no idea what I'm actually using".

**Comment by tokland** [comment]
Ok. It's unlikely progressbar is the issue, but some users had similar problems with the chunksize (only -1 worked for them on big videos).

**Comment by DavidVentura** [comment]
Yes, I'm pretty sure my connection is fixed now (it was giving me lots of
errors  for about 1 month). These videos are 500MB-1.7GB. I'll upload
another video today and see if it dies.



On 2 May 2016 at 12:58, Arnau Sanchez <notifications@github.com> wrote:

> Ok. It's unlikely progressbar is the issue, but some users had similar
> problems with the chunksize (only -1 worked for them on big videos).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tokland/youtube-upload/issues/106#issuecomment-216276327>
>



-- 
*Stack* is the new term for "I have no idea what I'm actually using".
