### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by PyRo1509** [tokland/youtube-upload#107]
`# youtube-upload -t "title" --privacy="unlisted" video.MOV

Using client secrets: /usr/local/share/youtube_upload/client_secrets.json

Using credentials file: /user/.youtube-upload-credentials.json

Start upload: video.MOV

100% |###########################################################################################################################################################################| Time: 0:34:02 979.3 KiB/s

Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 251, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 52, in catch_exceptions
    debug("[{0}] {1}".format(exc.__class__.__name__, exc))
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 36, in debug
    if should_encode else obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1473: ordinal not in range(128)`

I upload my videos to a VPS then youtube-upload to youtube.  This error is VERY common (25% of videos) in different videos.  I then tend to just reencode it to a bitrate higher than the original to limit loss.  Since it's a VPS i have 100mbit up capability.  It is a bit (pun intended) of a pain.

**Comment by tokland** [comment]
I never see that message, I cannot reproduce, sorry. Reopen if you have a reproducible command that triggers it.
