### ISSUE TITLE
client-secrets vs credentials-file?

### ISSUE THREAD

**Issue by nebukadnezar** [tokland/youtube-upload#109]
I'm having a slight confusion here - the Google OAuth2 API gives me one JSON file. Your instructions ask for a client-secrets file AND a credentials file. Which is which and where do I get the other?

**Comment by tokland** [comment]
The JSON you get from the API is the --client-secrets file. The JSON file that will be automatically created when you authenticate for the first time (when trying to upload a video) is the --credentials-file. Is that more clear? I'd have to update the README.

**Comment by nebukadnezar** [comment]
Ah, ok - now that makes sense. So for posteriority' sake:

The process was to give the command line a filename that doesn't exist yet
for the credentials-file parameter. Then run the upload script, and it then
asked to paste a URL into the browser. This URL takes you to a page where
you click "Allow" to allow the authentication token given in the next
screen access to the youtube account. I entered that token in return and
your script saved it to JSON file. So that part worked.

Interestingly though, it then ran into the following errror. Google now
seems to think I need to sign up to youtube first (which, of course, I have
done long ago...). Have you seen this error before?

Using client secrets: client_secrets.json
Using credentials file: credentials.json
Using category: Science & Technology (id=28)
Start upload: html/data/week_1080p.mov
[RequestError] Server response: {
 "error": {
  "errors": [
   {
    "domain": "youtube.header",
    "reason": "youtubeSignupRequired",
    "message": "Unauthorized",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Unauthorized"
 }
}

**Comment by nebukadnezar** [comment]
Resolved by using a google account that is NOT the domain manager account. Apparently one cannot use the admin account to post videos using this method.

**Comment by tokland** [comment]
Thanks for the detailed explanation. Not sure about using the domain manager accout, I have only one accound and it works.

**Comment by frongk** [comment]
I had this same issue:
[RequestError] Server response: {
"error": {
"errors": [
{
"domain": "youtube.header",
"reason": "youtubeSignupRequired",
"message": "Unauthorized",
"locationType": "header",
"location": "Authorization"
}
],
"code": 401,
"message": "Unauthorized"
}
}

I fixed it by going into YouTube and starting a channel for my YouTube account. Being able to use your Google account in YouTube isn't enough. You need to actually go to where you would upload a video in the account first.  I think that finalizes the "YouTubeSignupRequired" process?
