### ISSUE TITLE
ValueError: zero length field name in format

### ISSUE THREAD

**Issue by indariums** [tokland/youtube-upload#11]
youtube-upload --title="title" --description="latter" \
                --location="=" --client-secrets="/volumeUSB1/usbshare1-1/my_client_secrets.json" \
                 --category=Games --tags="tags" "/volumeUSB1/usbshare1-1/bs1.avi";  

File "/opt/local/bin/youtube-upload", line 164, in <module>
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/opt/local/lib/python2.6/site-packages/youtube_upload/lib.py", line 21, in catch_exceptions
    fun(*args, **kwargs)
  File "/opt/local/bin/youtube-upload", line 161, in main
    run_main(parser, options, args)
  File "/opt/local/bin/youtube-upload", line 119, in run_main
    debug("Using client secrets: {}".format(client_secrets))
ValueError: zero length field name in format

**Comment by j3dd4h** [comment]
The same problem for me and turn out due to missing Python Google API.
You can install by using command : pip install --upgrade google-api-python-client

**Comment by indariums** [comment]
Strange, but I installed Python Google API via easy_install --upgrade google-api-python-client.
Python 2.6

Searching for google-api-python-client
Reading http://pypi.python.org/simple/google-api-python-client/
Reading http://code.google.com/p/google-api-python-client/
Reading http://github.com/google/google-api-python-client/
Best match: google-api-python-client 1.3.1
Processing google_api_python_client-1.3.1-py2.6.egg
google-api-python-client 1.3.1 is already the active version in easy-install.pth

Using /volumeUSB1/usbshare1-1/@optware/local/lib/python2.6/site-packages/google_api_python_client-1.3.1-py2.6.egg
Processing dependencies for google-api-python-client
Finished processing dependencies for google-api-python-client

**Comment by tokland** [comment]
It seems python 2.6 needs numeric {N} indexes. Fixed: 94ab4f44
