### ISSUE TITLE
enabling content monetization

### ISSUE THREAD

**Issue by nebukadnezar** [tokland/youtube-upload#110]
Hi,
when using youtube_upload, I still have to manually apply content monetization on each video, despite the default setting for the channel being set to "monetization on". 

There appears to be an API way to do this, but that requires the uploader to be a Youtube partner with a CMS ID, which I am not. Is there any other way (scripted) that this can be enabled (other than via e.g. selenium, which looks very tempting for its simplicity...)?

**Comment by tokland** [comment]
Sorry, I have no more info on this, it seems to be as you say: https://developers.google.com/youtube/partner/upload_claim_sample.

It's unclear to me why don't use the default settings when uploading with the API.

I've never used Selenium with Youtube, I guess it should work.

**Comment by j4hangir** [comment]
Videos that are uploaded manually will be monetized by default (as set in **default channel upload settings**), yet those uploaded with the script need to be manually enabled. 

Isn't it script-related, or isn't there possibly other parameters that need to be sent along?

**Comment by tokland** [comment]
@j4hangir Yes, that's how Youtube API wors, there is no workaround that I know of.

**Comment by nebukadnezar** [comment]
Last time I checked (early this year), you needed to be a high volume VIP
customer of youtube's to be allowed to automatically monetise.
