### ISSUE TITLE
overflow error

### ISSUE THREAD

**Issue by kgeo** [tokland/youtube-upload#117]
On a Windows Server 2012 R2 Standard 64-bit system. I installed python 3.5.1 (32bit), did 
`pip install --upgrade google-api-python-client progressbar2` as suggested, and downloaded and `setup.py install`ed youtube-upload.

When running it, it starts uploading and the progress bar gets to a few percent then I get an overflow error as in the attached error message:

[py-error.txt](https://github.com/tokland/youtube-upload/files/329435/py-error.txt)

I have to add that on my personal Win10 machine with python 3.5.1 all works perfectly, and I used it quite a few times. I wanted to let our server do that periodically, which is why I try it on the server.

**Comment by tokland** [comment]
Which version are you using? 4b572c2 removed the use of progressbar.ETA with that problem.

**Comment by kgeo** [comment]
How do I check the version in the unzipped files?
As this will be running as a script, as a quick workaround, I actually uninstalled the progressbar before your seeing your comment and it now works ok.

**Comment by tokland** [comment]
Yes, uninstalling progressbar works because it's a bug on their part. 

> How do I check the version in the unzipped files?

You can't. But you can look into `youtube_upload/main.py` and check if there is a "progressbar.ETA()," there.

**Comment by kgeo** [comment]
Yep, there is. Ok, I'll download the updated version. Thanks!

**Comment by tokland** [comment]
Or just delete the line and re-install. Let me know if it works in #116
