### ISSUE TITLE
New releases

### ISSUE THREAD

**Issue by perpi** [tokland/youtube-upload#119]
As I see the source has changed during last months, but last release has been for July 2015. Will should still install the july-2015 version?

**Comment by tokland** [comment]
Do you mean github releases? Last one is 13Jan-2015. Anyway, I recommend using the master version.

**Comment by perpi** [comment]
yes: https://github.com/tokland/youtube-upload/releases

I've installed it via AUR: https://aur.archlinux.org/packages/youtube-upload-git --> https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=youtube-upload-git

**Comment by tokland** [comment]
Ok. Releases in github are not relevant, it's better just to use the git version as the AUR package does.
