### ISSUE TITLE
How to set "Video language", "Monitize" field when upload?

### ISSUE THREAD

**Issue by SnoOpyMinhThang** [tokland/youtube-upload#12]
= Versions

youtube-upload: 0.7.3
python: 2.7.8
python-gdata: 2.0.18

= Describe the steps (including the command you run) that will reproduce
the problem?

How to set "Video language" field when upload?
It's good to have --language option.
I need "Video language" set to English for all newly upload videos.

One more thing, how to set Monitize settings for video?
Ads settings can be set via Youtube Video Manager, but lack of automation insert Mid-roll ads based on video length.
I hear Gdata API v3 support it.
Please help me!
Dear,

**Comment by SnoOpyMinhThang** [comment]
Or at least,
newly uploaded videos should respect "Upload default" settings in Youtube channel where default "Video language", "Monitize" (limited Mid-roll ads, because video length only know when video process finished).

**Comment by tokland** [comment]
71bfa7dc
