### ISSUE TITLE
How to get iframe link

### ISSUE THREAD

**Issue by muhammadfarizarya** [tokland/youtube-upload#120]
Good morning, I just found you cool module here, but one thing want to know, can I get iframe link for emmbed video? or I must copied manually from youtube channel pages? 
Thank you

**Comment by tokland** [comment]
You usually would use youtube-upload from the command-line, I think uploading from a webpage with a form needs a different infrastructure, I don't know how it works, sorry. Check the API docs.

**Comment by tokland** [comment]
Sorry, I misunderstood your question. I am afraid you have to generate the link yourself, the API only returns the ID of the video. I'll check it.

**Comment by tokland** [comment]
This is the answer of the API, I don't see any info for what you want.

`` `
{
    'kind': 'youtube#video',
    'id': 'A3svGokHLxc',
    'status': {
        'embeddable': True,
        'uploadStatus': 'uploaded',
        'license': 'youtube',
        'privacyStatus': 'public',
        'publicStatsViewable': True
    },
    'snippet': {
        'title': 'title',
        'liveBroadcastContent': 'none',
        'defaultLanguage': 'en-US',
        'channelTitle': 'Arnau Sanchez',
        'localized': {
            'title': 'title',
            'description': ''
        },
        'publishedAt': '2016-07-12T19:01:36.000Z',
        'defaultAudioLanguage': 'en-US',
        'channelId': 'UCe2HLXFCqOymqTA6hobN8yg',
        'thumbnails': {
            'medium': {
                'url': 'https://i.ytimg.com/vi/A3svGokHLxc/mqdefault.jpg',
                'width': 320,
                'height': 180
            },
            'default': {
                'url': 'https://i.ytimg.com/vi/A3svGokHLxc/default.jpg',
                'width': 120,
                'height': 90
            },
            'high': {
                'url': 'https://i.ytimg.com/vi/A3svGokHLxc/hqdefault.jpg',
                'width': 480,
                'height': 360
            }
        },
        'categoryId': '1',
        'description': ''
    },
    'etag': '"5g01s4-wS2b4VpScndqCYc5Y-8k/VWDi1SNtPojDQHLqcE4TGhrEi88"'
}
```

**Comment by muhammadfarizarya** [comment]
I think so, thank you very much, I'll try another ways, thank you
