### ISSUE TITLE
Release on pypi

### ISSUE THREAD

**Issue by jleclanche** [tokland/youtube-upload#121]
Could you create a PyPI release? I'd like to package this for Arch Linux and it'd be a lot simpler if I could use the PyPI template.

**Comment by tokland** [comment]
Sorry, I prefer a versionless app. There are lots of AUR packages build from github, you can use them as a guide.

**Comment by tokland** [comment]
(But if you're willing to maintain the pypi package that would be another matter)

**Comment by Skylion007** [comment]
If you really want to install with pip you can always use the Git repo as a source like [so](https://stackoverflow.com/questions/8247605/configuring-so-that-pip-install-can-work-from-github). Not sure how well pip handles upgrades like this though.

**Comment by tokland** [comment]
Very cool, @Skylion007, didn't know you could do that with pip.
