### ISSUE TITLE
Can I upload videos in bulk? 

### ISSUE THREAD

**Issue by attiqfsd** [tokland/youtube-upload#126]
Hi,  I want to upload videos to YT in bulk. I can upload 1 video at time fine, but I need a bulk python uploader.

**Comment by perpi** [comment]
Use a bash/python loop

**Comment by qiuwei** [comment]
Put all of the videos in a folder, then youtube-upload * inside the folder.

**Comment by tokland** [comment]
@qiuwei: That's only to upload split videos, since they share all the metatags. @attiqfsd :To upload many different videos you must any shell language or scripting of your OS. You can ask in forums (i.e. stackoverflow)
