### ISSUE TITLE
Error loading (unable to process the file)

### ISSUE THREAD

**Issue by Hunter-Nomad** [tokland/youtube-upload#127]
Hi) 
Thank you for a wonderful plugin !! But sometimes when uploading it to video / youtube not noyavlyaetsya and channel video compre appears - / Error loading (unable to process the file).
How to solve this problem? Maybe can check the upload and if an error is re-upload or update video?

**Comment by tokland** [comment]
I have no idea, never say this error. You should paste the command you run and the output.

**Comment by tokland** [comment]
No feedback, closing.
