### ISSUE TITLE
Share own videos via google plus or twitter after upload and public video successfully

### ISSUE THREAD

**Issue by MrD37jncj** [tokland/youtube-upload#129]
Hi, can you ( can anyone) add options for share own videos via google plus or twitter after upload and public video successfully. Thank you.

**Comment by XylitolJ** [comment]
Yes,I also need this feature as well. it will be great if youtube-upload can do this

**Comment by tokland** [comment]
A script can upload the video, get the ID/URL and post it to google+, twitter, FB or the zillion places there are to publish things to, I don't think it makes sense to include such things in youtube-upload.
