### ISSUE TITLE
No Upload with credentials file

### ISSUE THREAD

**Issue by mooooonbaby** [tokland/youtube-upload#132]
Hi,

i've downloaded the JSON-Credentials-File from Google and could upload a file to youtube for the first time i used youtube-upload with this command line:

` youtube-upload --title="test" --credentials-file=client_secret_923898707427-d3si1p7179bn744jm9s527slp68rsumv.apps.googleusercontent.com.json ~/aaa.mp4`

then i've tested the upload to an other youtube-account, but it doesn't work. this is the error:

```
[RequestError] Server response: {
 "error": {
  "errors": [
   {
    "domain": "youtube.header",
    "reason": "youtubeSignupRequired",
    "message": "Unauthorized",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Unauthorized"
 }
}
```

i've deleted the youtube-upload folder and reinstalled it and tried it again with the working JSON, but this also works anymore. there is the same error.

whats wrong here?

**Comment by tokland** [comment]
Are you using a client_secret file with the --credentials-file option?

**Comment by mooooonbaby** [comment]
upps. but with --client_secrets i get this error:

```
 youtube-upload --title="test" --client-secrets="client_secret_923898707427-d3si1p7179bn744jm9s527slp68rsumv.apps.googleusercontent.com.json" aaa.mp4
Using client secrets: client_secret_923898707427-d3si1p7179bn744jm9s527slp68rsumv.apps.googleusercontent.com.json
Using credentials file: /home/pi/.youtube-upload-credentials.json
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 250, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 39, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 245, in main
    run_main(parser, options, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 173, in run_main
    youtube = get_youtube_handler(options)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 159, in get_youtube_handler
    get_code_callback=get_code_callback)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth/__init__.py", line 37, in get_resource
    flow = get_flow(client_secrets_file, scope=YOUTUBE_UPLOAD_SCOPE)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 2105, in flow_from_clientsecrets
    cache=cache)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/clientsecrets.py", line 166, in loadfile
    return _loadfile(filename)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/clientsecrets.py", line 127, in _loadfile
    return _validate_clientsecrets(obj)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/clientsecrets.py", line 90, in _validate_clientsecrets
    _INVALID_FILE_FORMAT_MSG + ' '
oauth2client.clientsecrets.InvalidClientSecretsError: Invalid file format. See https://developers.google.com/api-client-library/python/guide/aaa_client_secrets Expected a JSON object with a single property for a "web" or "installed" application
```

in one of yours examples you upload a file using 2 json-files. but i got only these one file from google. AND. it worked for the very first time i used youtube-upload.

**Comment by tokland** [comment]
> Expected a JSON object with a single property for a "web" or "installed" application

Check the structure of the JSON you are using and compare it with the client_secrets.json shipped with youtube-upload. There it has indeed a "installed" main key.

**Comment by mooooonbaby** [comment]
the structure is different, but the client_secret and the client_id are the same in both files (in client_sectrets.json and in the downloaded json). i've tested upload with the client_secret.json, but there is the same error.

i use youtube-upload on my raspberry pi. on my windows pc i use an other google account. maybe this makes problem? connecting to google with 2 accounts from 2 different computers with ONE ip address?

**Comment by mooooonbaby** [comment]
doesn't work, same error as before. i installed teh program again. the original client_secrets.json is completely different from the one you've linked. it much longer. is this normal? i've replaced the file with the file you've linked and replaced the client_secret and the client_id with the value from the json i've downloaded from google. then i tried

`youtube-upload --title="test" --client-secrets=client_secrets.json ~/aaa.mp4`

is the correct or wrong? should youtube-upload also work with the json i've downloaded? this is the strcuture of the file:

`{"installed":{"client_id":"012345678901-qwertzuiopasdfghjj.apps.googleusercontent.com","project_id":"dummy-dummy-111111","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://accounts.google.com/o/oauth2/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"1a2a3a4a5a7a8a9a0a0","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}`

something wrong with this file?

**Comment by tokland** [comment]
My knowledge of the Google API is superficial, I really don't know more than you. 

I just created a client_id.json like this:

https://console.developers.google.com/
google-api -> New Project
Project name: testing-youtube-upload
Create
Youtube Data API v3 -> Enable
- Go to credentials
 Which API: Youtube Data API v3
 Where calling: Other UI
 What data: User data
Create an OAuth 2.0 client ID
  Name: test
Download client_id.json

Delete ~/.youtube-upload-credentials.json to make sure the new secrets file is used.
$ youtube-upload -t title --client-secrets=client_id.json src/youtube-upload/test.mp4
nT8cQ_avWV0

Contents of `client_id.json`:

```
{"installed":{"client_id":"354761293870-th1v694u65cedgckid1q3f5ehorhjja7.apps.googleusercontent.com","project_id":"hopeful-host-128019","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://accounts.google.com/o/oauth2/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"qYzWdjC9L68SF7WWMGYzgJZ7","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}
```

**Comment by mooooonbaby** [comment]
worked - once. when i create a new project with a new client_id.json it doesn't work. this is the error:

> [RequestError] Server response: {
>  "error": {
>   "errors": [
>    {
>     "domain": "youtube.header",
>     "reason": "youtubeSignupRequired",
>     "message": "Unauthorized",
>     "locationType": "header",
>     "location": "Authorization"
>    }
>   ],
>   "code": 401,
>   "message": "Unauthorized"
>  }
> }

**Comment by mooooonbaby** [comment]
before every test i deleted ~/.youtube-upload-credentials.json

**Comment by tokland** [comment]
If you send to my email the clients json file i'll try it.

-- Mobile
