### ISSUE TITLE
Can not upload on mac os x 10.9.5

### ISSUE THREAD

**Issue by TheSneakySniper** [tokland/youtube-upload#133]
Is this program not supported on mac os x? I can't upload anything!!
The command is this:
youtube-upload --email=thesneakysniper@gmail.com --title="test.mp4" --api-upload --category="Tech" --private ~/Desktop/SPOT11_000001.AVI

It asks for my password:
Password for account <thesneakysniper@gmail.com>:
I enter my password CORRECTLY
then it says:
[BadAuthentication] Authentication failed

What am i doing wrong?

It has done this on every single youtube account i try...

what is going on??
Do i need a secrets file?

if thats the problem. please tell me.

**Comment by tokland** [comment]
You probably are using the old youtube-upload version from pip, the new one using API v3 does not has options email/password, using OAuth2 instead. Install directly from sources.
