### ISSUE TITLE
Trying to install from source

### ISSUE THREAD

**Issue by TheSneakySniper** [tokland/youtube-upload#134]
Here:
I download it
unzip it
then type sudo python /Downloads/youtube-upload/setup.py
gives me this error
sudo python Downloads/youtube-upload-master/setup.py 
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by tokland** [comment]
```
$ cd /Downloads/youtube-upload/
$ sudo python setup.py install
```

**Comment by TheSneakySniper** [comment]
ha... i am an idiot

**Comment by TheSneakySniper** [comment]
sudo python Downloads/youtube-upload-master/setup.py install
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
error: package directory 'youtube_upload/' does not exist

**Comment by TheSneakySniper** [comment]
Am i missing some packages?
Will this install if i install googleprogressbar, etc.. via pip?

**Comment by tokland** [comment]
Please try my suggestion.

**Comment by TheSneakySniper** [comment]
Alright... I think i got this...
All i need to install now is googleapiclient (from what this error is telling me, i think...)
ImportError: No module named googleapiclient.errors
I will install it and move the folder into the youtube-upload directory
along with all other repositories

**Comment by tokland** [comment]
Did you try? `$ pip install --upgrade google-api-python-client progressbar2`

**Comment by TheSneakySniper** [comment]
Yes.
It still gave me that error

**Comment by TheSneakySniper** [comment]
sudo pip install --upgrade google-api-python-client progressbar2
The directory '/Users/sneakysniper/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/sneakysniper/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: google-api-python-client in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: progressbar2 in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: httplib2<1,>=0.8 in /usr/local/lib/python2.7/site-packages (from google-api-python-client)
Requirement already up-to-date: six<2,>=1.6.1 in /Library/Python/2.7/site-packages/six-1.10.0-py2.7.egg (from google-api-python-client)
Requirement already up-to-date: uritemplate<1,>=0.6 in /usr/local/lib/python2.7/site-packages (from google-api-python-client)
Requirement already up-to-date: oauth2client<4.0.0,>=1.5.0 in /usr/local/lib/python2.7/site-packages (from google-api-python-client)
Requirement already up-to-date: python-utils>=2.0.0 in /usr/local/lib/python2.7/site-packages (from progressbar2)
Requirement already up-to-date: simplejson>=2.5.0 in /usr/local/lib/python2.7/site-packages (from uritemplate<1,>=0.6->google-api-python-client)
Requirement already up-to-date: rsa>=3.1.4 in /usr/local/lib/python2.7/site-packages (from oauth2client<4.0.0,>=1.5.0->google-api-python-client)
Requirement already up-to-date: pyasn1-modules>=0.0.5 in /usr/local/lib/python2.7/site-packages (from oauth2client<4.0.0,>=1.5.0->google-api-python-client)
Requirement already up-to-date: pyasn1>=0.1.7 in /usr/local/lib/python2.7/site-packages (from oauth2client<4.0.0,>=1.5.0->google-api-python-client)
sneaky:youtube-upload-master sneakysniper$ youtube-upload 
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 9, in <module>
    from youtube_upload import main    
  File "/Library/Python/2.7/site-packages/youtube_upload/main.py", line 24, in <module>
    import googleapiclient.errors
ImportError: No module named googleapiclient.errors

**Comment by tokland** [comment]
`google-api-python-client` should provide this module so I guess there is some kind of problem with your particular setup. I am sorry cannot give further advice as I don't know anything about Mac OS.

**Comment by TheSneakySniper** [comment]
Thats fine. I am very grateful for the help that you did give me. I managed to go to /usr/local/bin and found that for some reason even though i uninstalled it via pip, it was there...
I deleted that and now i am going to try to install it again.

I dont think it is a pip problem, but moreover the requisites that are needed for youtube-upload.

Can youtube-upload be installed on a 32 bit machine?

**Comment by TheSneakySniper** [comment]
Alright.
So i found this post
https://github.com/tokland/youtube-upload/issues/77

> I first did something heavy-handed and unwise by manually copying all the relevant modules from /usr/local/lib/python2.7/site-packages over to Library/Python/2.7/site-packages. This cleared some of the errors, but I was still getting crashes from the google api client code. I eventually found something in the Troubleshooting section of Google's Python documentation for the Tasks API, where it advises as follows:

Determine pip's install location with the following command:
pip show six | grep "Location:" | cut -d " " -f2
Add the following line your you ~/.bashrc file, replacing with the value determined above:
export PYTHONPATH=$PYTHONPATH:<pip_install_path>
Reload your ~/.bashrc file in any open terminal windows using the following command:
source ~/.bashrc
This resolved all the issues I was having, and I'm able to use youtube_upload as advertised. Thanks for checking!
This is interesting.
I will try this.

Maybe you could try and implement a feature where it searches first the original python directory then if none of the repositories are found, it searches the mac python directory?

That might fix the issues that us mac users are having.
