### ISSUE TITLE
Upload stops without readable error

### ISSUE THREAD

**Issue by Utty88** [tokland/youtube-upload#136]
Sometimes my Uploads do not succeed and I'm not able to figure out why. My upload is 10MBit so it should be at 1.1MiB/s. Sometimes when this happens it jumps immediately to 100% and the upload Speed goes Up to Speed I couldn't upload with.
Then the error with an empty Response is displayed...

> Using client secrets: /usr/share/youtube_upload/client_secrets.json
> Using credentials file: /root/.youtube-upload-credentials.json
> Your video will remain private until specified date.
> Using category: Gaming (id=20)
> Start upload: 38-Fadenlabyrinth.mkv
> 100% |#############################################################|   5.4 MiB/s
> [RequestError] Server response:

Do you have any idea to figure out what is wrong with the upload?

**Comment by tokland** [comment]
The server response is empty?

People has some times experience problems with the argument chunksize (default value: 4M). Try with -1. The problem is I can not reproduce it, my uploads always finish well.

**Comment by Utty88** [comment]
At least it does not print anything to the Putty Console running in Screen.

Do I change that directly in the upload_video.py or do I change that argument calling the tool like youtube-upload --chunksize=-1?

**Comment by tokland** [comment]
Directly in the code

-- Mobile

**Comment by Utty88** [comment]
Thank you!
With Setting it to -1 I got even the same ammount of Errors, but with changing it to 2M it works like a charm. Nevertheless could have also been an error with my ISP.
