### ISSUE TITLE
Sample for --credentials-file=my_credentials.json??

### ISSUE THREAD

**Issue by chikiuso** [tokland/youtube-upload#137]
Hi, my youtube has multiple channel , I read the document that it could point the script to upload to a specific channel with --credentials-file parameter, could you show a sample of my_credentials.json?? thanks.

**Comment by tokland** [comment]
It does not work this way. When you try to upload a video you'll be asked to get a code, this code will be bound to a user/channel. This will create a `~/.youtube-upload-credentials.json` that can be user to upload more videos to this user/channel.

**Comment by chikiuso** [comment]
I upload hundreds video, then I create a new channel. Then I just upload the new video, it doesn't ask me to input / select the channel, so I deleted the old .json one. It asks me for verification but now it shows the "Error: redirect_uri_mismatch".

**Comment by tokland** [comment]
Are you using the default client secrets shipped with the package?

**Comment by chikiuso** [comment]
I replace the parameters I got from developer console.

**Comment by chikiuso** [comment]
Sorry, my fault, It works now, thanks for help!!
