### ISSUE TITLE
Using * to upload an entire folder of videos.

### ISSUE THREAD

**Issue by TheSneakySniper** [tokland/youtube-upload#139]
Previously, i read that using * would not work in linux, and instead split up the videos... But it worked, and multiple videos were uploaded, with the ending [1/(how many videos there were being uploaded)]

**Comment by TheSneakySniper** [comment]
https://github.com/tokland/youtube-upload/issues/126

**Comment by tokland** [comment]
Each video has its own metadata, the multiple video was allowed to make easier to upload a splitted video. Anyway, I will remove this option in the new version. The script should be used to upload a single video.

**Comment by TheSneakySniper** [comment]
Please dont remove it :(
