### ISSUE TITLE
Feature request in 0.7.3 youtube-upload

### ISSUE THREAD

**Issue by SnoOpyMinhThang** [tokland/youtube-upload#14]
0.7.3 youtube-upload with
2.0.18 gdata python client
Youtube API have a lot of features that not include in youtube-upload.
I need to bulk update my playlists, set Video language option for video,...

You should write a document about how to implement Youtube API features in to youtube-upload via source code.
With this, user can create they owns features then can do "Pull request", you improve it and integrate into your code.
Rather than play alone :)

Dear,

**Comment by tokland** [comment]
Fair enough! 71bfa7dc

I'll close this, but feel free to send pull requests!
