### ISSUE TITLE
Upload video from path?

### ISSUE THREAD

**Issue by TheSneakySniper** [tokland/youtube-upload#140]
Is it possible to upload a video via the path?
e.g
youtube-upload -t testing /home/sniper/folderwherevideosare/video.mp4

it doesnt work

will this be added in the most recent version?

**Comment by TheSneakySniper** [comment]
I don't mind if you remove the * option, as long as there is the ability to upload from path.

**Comment by tokland** [comment]
This should work, always paste the full command/output on reports.

**Comment by TheSneakySniper** [comment]
Hmm. Now it seems to work. How odd.
It use to give me the IO error file not found..
But now it works.
