### ISSUE TITLE
Uploading with Unicode characters?

### ISSUE THREAD

**Issue by CommanderWayan** [tokland/youtube-upload#141]
Hi there!
What a nice program, so i wrote myself a python script that will bulk upload videos.
I have descriptions prepared in the folders, but unfortunately these contains unicode characters
e.g. • (\u2022)
So i read them an pass them to your script, and thats the point where i get an exception:

File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 23, in to_utf8
    return (s.decode(current).encode("UTF-8") if s and current != "UTF-8" else s)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 20: ordinal not in range(128)

in my string the character appears as \xe2\x80\xa2.
I cannot figure out the problem myself :(

**Comment by tokland** [comment]
I need a full command that fails so I can reproduce it.

**Comment by tokland** [comment]
No feedback.

**Comment by tokland** [comment]
No feedback.

**Comment by tokland** [comment]
No feedback.

**Comment by Colpocorto** [comment]
I have experienced same problem when trying to use UTF-8 with some Japanese kanjis on the description (it's a Windows 7 64 machine).

A example of a command line that fails:

python.exe d:\youtube-upload-master\build\scripts-2.7\youtube-upload -t "ART OF FIGHTING" -d "龍虎の拳 (c) 1992 SNK Corp." --client-secrets mysecrets.json --credentials-file mycreds.json d:\temp\output.avi

If I remove the japanese characters then it works perfectly.

**Comment by tokland** [comment]
Unfortunately it works with GNU/Linux and I don't have windows to test. In any case, paste the full output if someone can check it in windows.
