### ISSUE TITLE
ImportError: cannot import name util

### ISSUE THREAD

**Issue by Konstantinusz** [tokland/youtube-upload#143]
I get an error message when trying to upload, however it worked a few weeks ago:

```
Traceback (most recent call last):
  File "/usr/bin/youtube-upload", line 9, in <module>
    from youtube_upload import main    
  File "/usr/lib/python2.7/site-packages/youtube_upload/main.py", line 24, in <module>
    import googleapiclient.errors
  File "/usr/lib/python2.7/site-packages/google_api_python_client-1.4.0-py2.7.egg/googleapiclient/errors.py", line 26, in <module>
ImportError: cannot import name util

```

**Comment by tokland** [comment]
Is this related to youtube-upload? your installed google_api_python_client package seems to have problems. try reinstalling it. In StackOverflow or similar forums may help you.

**Comment by Konstantinusz** [comment]
Yes, I tried to upgrade it:
`sudo pip install --upgrade google-api-python-client`

**Comment by Konstantinusz** [comment]
Works now, I had to install pip2.7 
```
wget https://bootstrap.pypa.io/get-pip.py
sudo python2.7 get-pip.py
```
and then 
`sudo pip2.7 install --upgrade google-api-python-client`

**Comment by tokland** [comment]
Cool. Yes, there is usually a pip2 for 2.x and pip for 3.x
