### ISSUE TITLE
Multiple File Support

### ISSUE THREAD

**Issue by jrc03c** [tokland/youtube-upload#145]
Hey! I'm loving this project! I've been using it like crazy the past few weeks. But I have a quick question: is it possible to upload multiple files at a time with a single command? I mean, I can kick off multiple sessions manually, but I was just wondering if there was a way to upload multiple files, like this:

```
$ youtube-upload *.mp4
```

Thanks!

**Comment by tokland** [comment]
It's not possible, a lot of options are metadata (title, description, ...).
Why don't you simply use the shell? A for-loop or xargs may come handy.

**Comment by jrc03c** [comment]
Yeah, I could do that. I just don't know much about shell scripting. Maybe I'll try to whip up a Python script or something.

**Comment by tokland** [comment]
Python would

**Comment by tokland** [comment]
W
