### ISSUE TITLE
Request Error 503

### ISSUE THREAD

**Issue by jrc03c** [tokland/youtube-upload#146]
I tried uploading a video and got this error. Help? (I've been using this successfully for a couple of weeks and it just did this for the first time today!) Thanks!

```
[RequestError] Server response: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "backendError",
    "message": "Backend Error"
   }
  ],
  "code": 503,
  "message": "Backend Error"
 }
}
```

**Comment by tokland** [comment]
It worked before, it does not work now, and the error is "backendError". I'd say this is a temporal problem on Google servers and it will work again in some time (hopefully).

**Comment by jrc03c** [comment]
Okay, thanks.

**Comment by DinsFire64** [comment]
I would like to note this is incurring in increasing frequency for me as well. It is more than likely something on Google's end.

Interestingly enough I have three video files that fail to go up using the API, but go up fine using the YouTube upload page.

I have tried using a VPN to possibly hit another datacenter or a different node, but the same results have occured.

**Comment by tokland** [comment]
jrc03c does the error persist?

**Comment by jrc03c** [comment]
Haven't seen it in a few days...

**Comment by tokland** [comment]
Ok, closing issue.

**Comment by cnritng** [comment]
May be it's too fast transferring your data to youtube?!
