### ISSUE TITLE
[question] Send the work in background (and be notified of succeeded upload)

### ISSUE THREAD

**Issue by giopas** [tokland/youtube-upload#147]
Hi,

I am testing your script and it seems working. The question I have is if it is possible to send it in background so that even if the ssh connection to my server falls I have not the upload process stuck.

As I have already tested the script my authentication code has been already accessed. Can I now run the script and send it in background with a simple "&" or is there another better way to do so?

Thanks!

**Comment by tokland** [comment]
Use screen or tmux.
