### ISSUE TITLE
Upload speed limit parameter

### ISSUE THREAD

**Issue by hhiru** [tokland/youtube-upload#149]
This is probably my fault because I can't use github but I tried using the Pull request tab without results, sorry again :/

Anyway, I just wanted to suggest a upload speed limiter feature since I (and probably other people) have a bad and weird internet that completely saturate the internet latency while using the whole upload bandwidth. A parameter to limit said upstream bandwidth may really help. Thanks for your work!

**Comment by tokland** [comment]
That would be cool, but as the readme explains, I won't implement new features. I'd definitely merge it if someone made a PR, though.
