### ISSUE TITLE
How to Bulk Upload Video using Youtube-Upload?

### ISSUE THREAD

**Issue by joglomedia** [tokland/youtube-upload#15]
I am trying using youtube-upload to upload some videos in a time (bulk), but failed, always asking for Enter verification code: (which is done when using single video upload)

is there any method to bulk upload video using youtube-upload?

thanks

**Comment by tokland** [comment]
Once you upload a video, a credentials file should be created (default: .youtube-upload-credentials.json, change with --credentials-file) and you may use it to upload more videos.

**Comment by zzm88** [comment]
@tokland 
youtube-upload --title="title" 1.mp4;youtube-upload --title="title" 2.mp4;....and more
I used the command above to do bulk upload. But is there a better way to do so?
like "youtube-upload some-folder-name" to upload all files under a folder?

And how can I call the upload function in a python file?
