### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1441: ordinal not in range(128)

### ISSUE THREAD

**Issue by f3bruary** [tokland/youtube-upload#150]
I get this randomly during upload. Command: 
`youtube-upload --title test1 --description "test" --privacy unlisted /media/usb0/test.mp4`

Output:
`Using client secrets: /usr/local/share/youtube_upload/client_secrets.
Using credentials file: /home/user/.youtube-upload-credentials.json
    Start upload: /media/usb0/test.mp4
    100% |#######################################################################################################################################################|  40.8 MiB/s
    Traceback (most recent call last):
      File "/usr/local/bin/youtube-upload", line 10, in <module>
        main.run()
      File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 250, in run
        sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
      File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 39, in catch_exceptions
        fun(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 247, in main
        raise RequestError("Server response: {0}".format(bytes.decode(error.content).strip()))
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1441: ordinal not in range(128)`

**Comment by tokland** [comment]
Can you try ed5209e4?

**Comment by f3bruary** [comment]
```
...SNIP...
100% |################################################################|  34.3 MiB/s
[RequestError] Server response:
```

Not sure if there's a verbose or debug switch available. Let me know if I can help any further.

**Comment by tokland** [comment]
I don't understand, it shows no response. Maybe you can simply to try (main.py, line 248):
```
raise RequestError("Server response: {0}".format(error.content))
```

**Comment by f3bruary** [comment]
I don't understand what you mean.

**Comment by f3bruary** [comment]
Do you have a solution yet ?

**Comment by tokland** [comment]
No, sorry. Pull requests welcome.

-- Mobile

**Comment by borecole** [comment]
Had the same problem today, tried also to replace the line 248 as commented, but same issue. Adding just "print response" also doesn't worked. But most likely since the third and fourth try were working (same file).

**Comment by LNJ2** [comment]
I have the same bug:
```
hui@hui ~> youtube-upload -t "The Title" theverynicevideo.1080p.mkv 
Using client secrets: /usr/local/share/youtube_upload/client_secrets.json
Using credentials file: /home/mt/.youtube-upload-credentials.json
Start upload: theverynicevideo.1080p.mkv
100% |##################################################################################################|   7.9 MiB/s
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 251, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 42, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 248, in main
    raise RequestError("Server response: {0}".format(response))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 1441: ordinal not in range(128)
hui@hui ~>
```

**Comment by sezeryalcin** [comment]
Using credentials file: /root/.youtube-upload-credentials.json
Start upload: /NAS/PROCESS/some_file.2016-10-17_Mon.mp4
100% |##############################################################################################################################################################################| Time: 0:08:10  24.0 MiB/s
Traceback (most recent call last):
  File "bin/youtube-upload", line 10, in <module>
    main.run()
  File "/NAS/svn/trunk/webcam/tools/youtube-upload/bin/../youtube_upload/main.py", line 251, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/NAS/svn/trunk/webcam/tools/youtube-upload/bin/../youtube_upload/lib.py", line 39, in catch_exceptions
    fun(*args, **kwargs)
  File "/NAS/svn/trunk/webcam/tools/youtube-upload/bin/../youtube_upload/main.py", line 248, in main
    raise RequestError("Server response: {0}".format(bytes.decode(error.content).strip()))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1441: ordinal not in range(128)
Upload failed, skipped!

**Comment by sezeryalcin** [comment]
It fails for some files. I can try to help as I dealt with Python's stupidity with encoding and EXCEPTIONS.

It looks like it fails after it uploads. Can you just force encoding to ascii. I think you need to add ignore to encoding so that process should not fail.

.encode('ascii', 'ignore')

**Comment by tokland** [comment]
@sezeryalcin : yes, please, PR most welcome!

**Comment by sezeryalcin** [comment]
Cool
