### ISSUE TITLE
Video longer than 15 minutes failed on youtube

### ISSUE THREAD

**Issue by Sunka** [tokland/youtube-upload#151]
Same problem here like in issue #58 .
Video uploaded but the error message said " This video has been removed because it is too long. "
It is 25 minutes long video.
I have enabled in youtube settings for upload videos longer than 15 minutes.
Any help?

**Comment by NeoTheThird** [comment]
Might be related to #153. Try my hotfix, i can now  upload 60 minute videos.

**Comment by shvets-alex** [comment]
May be this?: https://support.google.com/youtube/answer/71673?hl=en

**Comment by kootsoop** [comment]
#58 and #153 are now closed. Closing here.
