### ISSUE TITLE
Upload just stops

### ISSUE THREAD

**Issue by DatDraggy** [tokland/youtube-upload#152]
I'm unsure why this is happening. When I try to upload a vid, it does so for the first 1-4% but then it just stops and freezes. The speed stays the same and the progress bar doesn't move.
Any ideas?

**Comment by filipac** [comment]
i have the same problem! Something may have changed in the API

**Comment by tokland** [comment]
I will be out some days, i'll check it at home

-- Mobile

**Comment by hdid** [comment]
Edit youtube_upload/upload_video.py and in line 33 change chunksize=4*1024*1024 to chunksize=2*1024*1024

**Comment by DatDraggy** [comment]
@hdid Thanks will try. Why do you think will this fix it?

**Comment by hdid** [comment]
Seems this issue is because of unstable connection. This is a temporary solution untill tokland fix it

**Comment by cyberplant** [comment]
I'm having a similar problem.. randomly it uploads all the file and then fails with "backend error".

Wasn't able to figure out what was happening.. I'm trying now with a different chunk size and retries.

**Comment by alfablac** [comment]
Point out the same thing here: https://github.com/tokland/youtube-upload/issues/179

It has not been reliable for uploads.

**Comment by kootsoop** [comment]
Closing as duplicate of #179
