### ISSUE TITLE
Retry Option?

### ISSUE THREAD

**Issue by userlip** [tokland/youtube-upload#155]
Had this output today aswell (more than once):

```
100% |################################################################|  10.6 MiB/s
[RequestError] Server response:
```

Would be useful to have a retry option!

Thank you!

**Comment by topik** [comment]
I'm getting the same output today. Also I think there is some problem with API speed, because I can't reach more than 1.5M/s and almost 90% of my uploads fails. Youtube can't proccess them. 
![image](https://cloud.githubusercontent.com/assets/3578443/22314857/b563efa4-e363-11e6-8099-09079e4ccc12.png)

**Comment by userlip** [comment]
Same here. I am getting these "Preparing Upload" thingys very often myself! (But only on Videos that are a bit longer - short videos work very fine!)

**Comment by userlip** [comment]
I think I fixed it - still running some tests but I am able to upload 10 GB big files without problems now! Will create a workable fork ASAP

**Comment by ManuCart** [comment]
For retry option I use this script
https://github.com/ManuCart/RaspberryPi/blob/master/scripts/youtube-upload
hope this help you

**Comment by userlip** [comment]
@ManuCart Thanks for the script! Mind helping me understand what the script does and how exactly the script know if the upload failed ? Thanks!

**Comment by ManuCart** [comment]
first script sort files and upload them
second when an upload fail, it's retry again and again
I just need to delete fails upload in youtube
I use it with a raspberry pi to upload basketball team matches
After that I use youtube editor to merge files
last line just tell me when it's finished

**Comment by userlip** [comment]
Thanks!

**Comment by topik** [comment]
@userlip yo, any ETA? I'm uploading one video whole day 😞 thanks

**Comment by userlip** [comment]
I am currently uploading ~50 videos all between 2 and 15 GB so far only one failed! Ill upload the changes now on my fork!

**Comment by topik** [comment]
I think it's working! I tried to change `chunksize` to 10MB but I see you completely removed them. Thanks a lot 😄

**Comment by userlip** [comment]
Yep and I also uped the max_retries (you may want them to be even higher for very long videos)

**Comment by hdid** [comment]
Seems that it does not resolve the problem!

**Comment by userlip** [comment]
@hdid what error are you getting and how often have you tried ?

**Comment by topik** [comment]
@hdid are you sure u are running userlip's version? It's working for me. Uploaded like 20 videos already (only 1 error).

**Comment by hdid** [comment]
@userlip No error but freezes randomly between uploads..
@topik Yup!

**Comment by userlip** [comment]
@hdid you have to keep in mind, that my version has **no** progressbar! And if you upload via the api youtube does **not** show the upload progress!

**Comment by topik** [comment]
@userlip than you are not using his version. just download it, install it and run it from location where its installed, in my case `/home/topik/youtube-upload-master/bin/youtube-upload`

**Comment by userlip** [comment]
Also try to purge the older version!

**Comment by hdid** [comment]
Yes i know about your fork and progressbar.. I usually build a source dist for easy management with pip like this [youtube-upload-0.8.0-userlip.tar.gz](https://github.com/tokland/youtube-upload/files/736477/youtube-upload-0.8.0-userlip.tar.gz)

I tested your version but i could not upload anything. With original version it is 50 50 success chance on upload!

**Comment by userlip** [comment]
Then your Internet connection is not stable enough. My version uploads the file in 1 chunk and if it fails it fails. tokland's versions sends the file in little chunks which is is a safer way to do it if your connection is not stable

**Comment by scaidermern** [comment]
Same problem for me. The upload failed with an empty error message:

```
Start upload: howToDestroyCapitalism.mp4
 31% |#############                         | 916.3 KiB/s[Retryable error 1/10] BadStatusLine (''). Wait 1.2 seconds
 82% |##############################        | 944.7 KiB/s[Retryable error 2/10] BadStatusLine (''). Wait 0.6 seconds
100% |######################################| 954.2 KiB/s
[RequestError] Server response:
```

A manual retry succeeded.

**Comment by kootsoop** [comment]
@userlip Can you propose a PR to fix? Or at least show what you did?  Closing as this seems old now.
