### ISSUE TITLE
Unicode Problem (Hebrew TItle and Description)

### ISSUE THREAD

**Issue by zuntah** [tokland/youtube-upload#156]
Hi
I'm trying to upload a video with Hebrew Title, Description, Playlist and Keywords.

There are question marks on youtube instead of hebrew when I'm trying to upload

**CMD:**
`youtube-upload --title="תאגד פרק 6 עונה 1 לצפייה ישירה עובד 100% איכות גבוהה" --description="הלינק לפרק המלא: \n\nhttp://viid.me/qgOwFh\n\nתאגד פרק 6 עונה 1 לצפייה ישירה עובד 100% איכות גבוהה\n\nתאגד פרק 6 בחינם\n\nתאגד פרק 6 לצפייה ישירה איכותי מאוד\n\nתאגד פרק 6\n\nתאגד עונה 1 פרק 6 לצפייה ישירה בחינם בלעדי איכות HD\n\nתאגד כל הפרקים לצפייה ישירה" --tags="תאגד פרק 6 בחינם לצפייה, תאגד פרק 6 לצפייה ישירה, תאגד לצפייה ישירה, תאגד פרק 6" --playlist="﻿תאגד פרק 35" --category="Entertainment" --client-secrets="upload/secret.json" ./uploads/queue/0.mp4`

**Output:**
```
Using client secrets: upload/secret.json
Using credentials file: [Censored]\.youtube-upload-credentials.json
Using category: Entertainment (id=24)
Start upload: ./uploads/queue/0.mp4
Video URL: https://www.youtube.com/watch?v=[Censored]
Adding video to playlist: [Censored]
[Censored]
```

**Result in youtube:**
http://i.imgur.com/5b2ACSi.png

You help is appriciated!
Thanks

**Comment by KenSharp** [comment]
What operating system? I've managed to upload using a whole host of language scripts.

Examples:
https://www.youtube.com/watch?v=mXqIiGl68mI
https://www.youtube.com/watch?v=2_3u5roZL9I
https://www.youtube.com/watch?v=I8B6FW_mdOE
I should have examples in Arabic, Hebrew and possibly Yiddish too but I simply can't find them.

These were uploaded in exactly the same way as your example, albeit wrapped in a Bash script to automate mass uploads. I'm using Linux and as a result everything is UTF-8 aware. It seems unlikely to be a problem with the script as the title and description is passed through unchanged. Or how old is your Python?
