### ISSUE TITLE
Change verification/Uploads go straight to same channel

### ISSUE THREAD

**Issue by IAmAbszol** [tokland/youtube-upload#158]
So when I first used the program I got a request to verify my account to use this program. After that whenever I add the code add the bottom from my json file, it doesnt seem to use it. Is there a key stored on the system to selete that can cause the program to look at the code and upload to a different account?

**Comment by IAmAbszol** [comment]
On Linux, remove the .youtube* credentials, I also removed them from my /usr/local/share if I recall.

**Comment by sweenig** [comment]
Any other ideas where it may be stored? I just want to clear the current credentials out so that i can authorize a different account to upload to.

**Comment by IAmAbszol** [comment]
It's been awhile but I believe it was stored into the home directory of your user folder.
