### ISSUE TITLE
EOFError: EOF when reading a line

### ISSUE THREAD

**Issue by MaxCodeX** [tokland/youtube-upload#16]
when i run youtube-upload, i give a error

Enter verification code: Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 164, in <module>
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 21, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/bin/youtube-upload", line 161, in main
    run_main(parser, options, args)
  File "/usr/local/bin/youtube-upload", line 121, in run_main
    youtube = youtube_upload.auth.get_resource(client_secrets, credentials)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth.py", line 40, in get_resource
    credentials = _get_credentials(flow, storage, get_code)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth.py", line 32, in _get_credentials
    return _get_credentials_interactively(flow, storage, get_code_callback)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth.py", line 20, in _get_credentials_interactively
    code = get_code_callback(authorize_url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/auth.py", line 14, in _get_code_from_prompt
    return raw_input("Enter verification code: ").strip()
EOFError: EOF when reading a line

 help me

**Comment by tokland** [comment]
Never seen that, you run this from the command line? paste the command.

**Comment by tokland** [comment]
No feedback. Closing.

**Comment by pavankumarts007** [comment]
I also came across same error when serving through apache

[Tue Sep 04 17:00:30.471555 2018] [wsgi:error] [pid 31310]
[Tue Sep 04 17:00:30.471568 2018] [wsgi:error] [pid 31310]     return input("Enter verification code: ")
[Tue Sep 04 17:00:30.471579 2018] [wsgi:error] [pid 31310]
[Tue Sep 04 17:00:30.471591 2018] [wsgi:error] [pid 31310] EOFError: EOF when reading a line

<img width="912" alt="github" src="https://user-images.githubusercontent.com/21104081/45029486-6d32d200-b066-11e8-9286-70aa2d35bf97.png">

**Comment by tokland** [comment]
@pavankumarts007 That's normal if the script it's run without a terminal and no authentication file is found, will ask for a code. Did you try to upload a video so the auth file is cached?

**Comment by pavankumarts007** [comment]
If i do runserver the code works well with credentials and clients secrets but when i serve same with apache EOF occurs may be via apache.

**Comment by tokland** [comment]
Where does $HOME point to when the script is run from Apache?

**Comment by pavankumarts007** [comment]
I got the point but unable proceed currenty when i run via runserver i get this paths
Using client secrets: /home/ubuntu/directory_indexer/indexer_project/client_secret.json
Using credentials file: /home/ubuntu/.youtube-upload-credentials.json
but how do i set $HOME path to  /home/ubuntu/

**Comment by tokland** [comment]
I am not sure how to change this in Apache, but it's probably easier just to copy the files where Apache is looking for them and be done with it.

**Comment by pavankumarts007** [comment]
Finally found the solution while serving via apache.
Apche looks at path /var/www/.youtube-upload-credentials.json
 instead of /home/ubuntu/.youtube-upload-credentials.json
so i copied the file and provided permission now works like charm .
Thanks for the immediate help.
Finally could you please please provide this info in Readme.md so that other fellows will get the point when they serve their application via Apache.

**Comment by tokland** [comment]
Cool. I'll accept PR on about the README.
