### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by MelcomX** [tokland/youtube-upload#162]
Hello

I'm having an error, when uploading an Video to youtube.:

`UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 1441: ordinal not in range(128)`

I had the same file uploaded to an other Youtube-channel, from the same machine, with no erros. The command I used is:
`youtube-upload --title="Title" 1.mp4`
I think it's a bug, but I can't say what it is...

**Comment by KenSharp** [comment]
What is your operating system? UTF works fine for me on Linux.

**Comment by kootsoop** [comment]
Seems like a duplicate of #216
