### ISSUE TITLE
README.md does not explain diff between client-secrets and credentials-file params

### ISSUE THREAD

**Issue by androclus** [tokland/youtube-upload#163]
hey, all..  first of all, thank you for this script!  much appreciated to have something available from command-line (i am just bash-ing on linux).

i have gotten it going, but only with a browser-auth.

as a newbie to doing YT uploads with this python script, and also new to setting up an OAuth 2.0 arrangement with Google, i find myself asking for more explanation in the README.md file regarding the two parameters, _client-secrets_ and _credentials-file_.  these seem to be separate available parameters, but in the README.md instructions, they seem to be combined into a single concept.

in the "**Examples**" section of the README.md, it shows one example of using the youtube-upload script with many more parameters. two of these are:

>   --client-secrets=my_client_secrets.json \
>   --credentials-file=my_credentials.json \

but the difference between these two parameters, _client-secrets_, vs _credentials-file_, is not explained.

so as a newbie i am left with the un-answered questions: do i need both parameters? or just one? if both, how do i generate the second credentials file?  if one, which one do i use?  alternatively, is one parameter needed, the other optional? if so, why or when?  or, can one use only one, but NOT both?

looking for clues by backing up again to the the immediately preceding section, "**Authentication**", i am further confused, where it says,

Use this JSON as your credentials file: --client-secrets=CLIENT_SECRETS

so that instruction uses BOTH the phrases, "credentials file" and "client secrets" all in the same concept, combining them into one, again making no distinction for me which helps me understand.

so i try to use only the --client-secrets=MY_CLIENT_ID_FILE.json parameter.  it does work, but only by requiring an additional external browser authentication.  but i need this to work from command-line only, which is what i thought the purpose of this script was.

i may be missing something obvious (it's been known to happen! :P ) and if so, please let me know. otherwise, as a first time user, i really need to have more explanation as to how to use these two parameters and when.

i am on ubuntu 16.10, and using the version of youtube-upload available here today. please let me know if you need any more info / details.

thanks, all.
-jeff

**Comment by NeoTheThird** [comment]
Same confusion here, please explain :)

**Comment by NeoTheThird** [comment]
Baded on the documentation over at https://github.com/porjo/youtubeuploader i think you need to copy the strings from the json file. I'll test it.

**Comment by NeoTheThird** [comment]
Nope, that's not it.

**Comment by LUS1N** [comment]
@tokland pls help

**Comment by tokland** [comment]
It's simple:

- `client_secrets.json`: Identifies the application. `youtube-upload` ships with a default one, but the README advises to generate your own to avoid problems with the quota. 
- `credentials.json`: Identifies your specific user in google/youtube so you can upload videos to your channels. This is generate on the first upload and then reused.
