### ISSUE TITLE
[dailyLimitExceeded] Can't upload anything

### ISSUE THREAD

**Issue by lgis80boy** [tokland/youtube-upload#164]
[RequestError] Server response: {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceeded",
    "message": "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube/quotas?project=911313852664",
    "extendedHelp": "https://console.developers.google.com/apis/api/youtube/quotas?project=911313852664"
   }
  ],
  "code": 403,
  "message": "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube/quotas?project=911313852664"
 }
}

**Comment by one2gov** [comment]
change content of /usr/local/share/youtube_upload/client_secrets.json to what you got in this step https://github.com/tokland/youtube-upload#authentication

**Comment by Utty88** [comment]
I had the same issue.
After replacing /usr/local/share/youtube_upload/client_secrets.json I also had to delete my token in .youtube-upload-credentials.json. With the next upload the script asks again for authorization which should do the trick.

**Comment by paolo-italy** [comment]
I use the uploader to automate the upload of about 50 videos per day since october 2016. Starting from last week I am experiencing the "dailyLimit" error. Note that I am using a Google Apps for Business account (paid), and a client-secrets.json file generated by the Google Console.
Is something wrong with APIs in these days?

**Comment by Utty88** [comment]
As written in my comment above you. Please try t remove your token. It's in the users or roots home directory and named: ".youtube-upload-credentials.json".
After that you have to reauth to Youtube. This fixed the issue for me.

**Comment by paolo-italy** [comment]
I tried this the first time it happened, but it didn't solve the problem. The only solution was to switch to another (free Gmail) account, create a new project, etc.
The main problem is that the upload operation has to be performed during the night, and it stops randomly. I have to wait 9AM to resume download...

Note that I am using

**Comment by KenSharp** [comment]
Is your script retrying failed uploads? They're failing a LOT and not due to youtube-upload, but may be due to the V2 API.

**Comment by paolo-italy** [comment]
Originally I was using the tokland version, but in the last period it failed quite often, refusing to upload.
Moved to userlip it never fail, but yes, I suppose it retries to upload; I don't know how many times.

I have an average of 50 videos per day, if a video costs 1600 units and I have 1 million units a day, it should retry 625 times...

The strange thing is I have no stats at all for my account in the develop console.

**Comment by theChaosCoder** [comment]
I get the same msg. I tried every suggestion from here, no luck (used only 10k from quota). Then I made a test and tried to upload a video via the webpage -> same result. 

So it seems google made some restrictions. 
Btw, I have a fresh account.

**Comment by tokland** [comment]
Create you own `client_secrets.json` as explained in the README.

**Comment by tokland** [comment]
Duplicate #174
