### ISSUE TITLE
dailyLimitExceeded

### ISSUE THREAD

**Issue by wafebreaker** [tokland/youtube-upload#165]
[RequestError] Server response: {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceeded",
    "message": "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube/quotas?project=911313852664",
    "extendedHelp": "https://console.developers.google.com/apis/api/youtube/quotas?project=911313852664"
   }
  ],
  "code": 403,
  "message": "Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube/quotas?project=911313852664"
 }
}

I have this error. Already changed content of /usr/local/share/youtube_upload/client_secrets.json still not working.

Ideas?

**Comment by Utty88** [comment]
#164

**Comment by tokland** [comment]
Duplicate #174
