### ISSUE TITLE
Access forbidden...

### ISSUE THREAD

**Issue by Scuottolinx** [tokland/youtube-upload#166]
[RequestError] Server response: {
 "error": {
  "errors": [
   {
    "domain": "youtube.common",
    "reason": "forbidden",
    "message": "Access forbidden. The request may not be properly authorized."
   }
  ],
  "code": 403,
  "message": "Access forbidden. The request may not be properly authorized."
 }
}

I followed the guide, but Google keeps telling me that I can not log on.

**Comment by esturcke** [comment]
I was seeing this as well. In my case I was hitting a rate limit. When I tried to upload though youtube.com directly I got:

> The upload has failed because you uploaded too many videos in a short time. You'll need to wait before uploading more videos.

**Comment by KenSharp** [comment]
A lot of people are seeing this, not only youtube-upload users. This isn't a bug.

**Comment by KenSharp** [comment]
Same reason as #164

**Comment by pepzwee** [comment]
I was having this issue as well. Not the `dailyLimit` one but `not properly authorized`, after getting new secrets I was still getting that error, but it seems like the upload credentials json file didn't have the right permissions. After I did a quick `chown` and `chmod` it started working again.

**Comment by kootsoop** [comment]
Closing, as this is a Google issue.
