### ISSUE TITLE
How to add --publish-at

### ISSUE THREAD

**Issue by niammuddin** [tokland/youtube-upload#172]
I use --publish-at="2016-03-10T15:32:17.0Z" 

but upload update is not change

**Comment by Utty88** [comment]
I use this, which works fine: --publish-at="2017-3-24T20:00:00.000+01:00"

**Comment by Djidiouf** [comment]
All the following works:

```
2017-05-12T14:00:00.0+00:00
2017-05-12T14:00:00.0+0000
2017-05-12T14:00:00.0+00
2017-05-12T14:00:00.0Z
```

Z stands for UTC (also known as Zulu time).
Note that you can't set a date and time prior to now().

**Comment by KenSharp** [comment]
> I use --publish-at="2016-03-10T15:32:17.0Z"

That date is in the past.

**Comment by kootsoop** [comment]
@niammuddin : As @KenSharp says, you're trying to publish a video in the past... you can only publish at the current or future times.
