### ISSUE TITLE
How can i access the video-url?

### ISSUE THREAD

**Issue by DrizztOne** [tokland/youtube-upload#177]
I have the following problem. I run a script on my server which uploads the videos automaticly to youtube. Now i want to access the url and save them in a database. The problem is i dont know how to access them. Can anyone help?

**Comment by Pavel-II** [comment]
simple.
run script as 
`./youtube-upload-master/bin/youtube-upload .... VIDEOFILE.mp4 > log`

and in log file you can see video ID
`https://www.youtube.com/watch?v=ID`

It might be a good idea to modify the loading script to run scripts after a successful download?
