### ISSUE TITLE
Upload fails on certain videos.

### ISSUE THREAD

**Issue by TomatoCo** [tokland/youtube-upload#179]
I successfully uploaded a 15 second, 22mb clip, as a test. I then went to upload a 1h16m, 42gb clip to show a friend some raw footage of a game. This upload does not seem to work. The upload speed quickly stabilizes on 1.1MiB/s and does not exhibit any further action. Clicking the video in the video manager, even one second after starting the upload, gives me a banner that says "Thank you! Your upload is complete."

**Comment by alfablac** [comment]
I'm also having problems lately uploading.
Using the Youtube native uploader (the one in the site), I can max my connection (30 MB/s).
However, if I use youtube-upload I can only achieve unstable speeds that tops on ˜17MB/s.
Some videos the upload speed just stops and then I receive
```
Traceback (most recent call last):
  File "C:\youtube-upload-master\youtube-upload-master\bin\youtube-upload", line 10, in <module>
    main.run()
  File "C:\youtube-upload-master\youtube-upload-master\bin\..\youtube_upload\main.py", line 251, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "C:\youtube-upload-master\youtube-upload-master\bin\..\youtube_upload\lib.py", line 42, in catch_exceptions
    fun(*args, **kwargs)
  File "C:\youtube-upload-master\youtube-upload-master\bin\..\youtube_upload\main.py", line 248, in main
    raise RequestError("Server response: {0}".format(response))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1441-1443: ordinal not in range(128)
```
on the log.
I'm using a batch script to upload files from a directory to youtube and e-mail me the log (as well the youtube link), but youtube-upload has not been reliable for such task atm.

**Comment by tokland** [comment]
The only tweakable parameter is the chunksize. I've set it now to 8M and added an option --chunksize. Please try bigger values.

587e843
