### ISSUE TITLE
setup.py not installing client_secrets.json

### ISSUE THREAD

**Issue by kldavis4** [tokland/youtube-upload#18]
Ran 'sudo python setup.py install'. Script installed but did not create /usr/share/youtube_upload. Manually creating and copy client_secrets.json there fixes error. This is on Ubuntu 14.04 LTS (ami-d05e75b8 in EC2).

**Comment by tokland** [comment]
Cannot reproduce, works for me:

```
$ sudo python setup.py install
running install
running build
running build_py
copying youtube_upload/upload_video.py -> build/lib/youtube_upload
copying youtube_upload/lib.py -> build/lib/youtube_upload
copying youtube_upload/main.py -> build/lib/youtube_upload
running build_scripts
copying and adjusting bin/youtube-upload -> build/scripts-3.4
running install_lib
copying build/lib/youtube_upload/upload_video.py -> /usr/lib/python3.4/site-packages/youtube_upload
copying build/lib/youtube_upload/lib.py -> /usr/lib/python3.4/site-packages/youtube_upload
copying build/lib/youtube_upload/main.py -> /usr/lib/python3.4/site-packages/youtube_upload
byte-compiling /usr/lib/python3.4/site-packages/youtube_upload/upload_video.py to upload_video.cpython-34.pyc
byte-compiling /usr/lib/python3.4/site-packages/youtube_upload/lib.py to lib.cpython-34.pyc
byte-compiling /usr/lib/python3.4/site-packages/youtube_upload/main.py to main.cpython-34.pyc
running install_scripts
copying build/scripts-3.4/youtube-upload -> /usr/bin
changing mode of /usr/bin/youtube-upload to 755
running install_data
creating /usr/share/youtube_upload
copying client_secrets.json -> /usr/share/youtube_upload
running install_egg_info
Removing /usr/lib/python3.4/site-packages/youtube_upload-0.8.0-py3.4.egg-info
Writing /usr/lib/python3.4/site-packages/youtube_upload-0.8.0-py3.4.egg-info
arnau@latitude:~/src/youtube-upload$ ls /usr/share/youtube_upload
client_secrets.json
```

Any idea?

**Comment by kldavis4** [comment]
Did you try it on a fresh EC2 instance? There may be something about the AMI I am using. Reported in case someone else runs into the same issue.

**Comment by DavidVentura** [comment]
Happened on debian jessie yesterday

**Comment by tokland** [comment]
Guys, I have no Debian/Ubuntu to test so I'll need some help here.

**Comment by kldavis4** [comment]
I think I found the problem. It looks like sys.prefix is '/usr/local' instead of '/usr' on the Debian version of distutils (see https://wiki.debian.org/Python#Deviations_from_upstream), so the client_secrets.json is getting installed in /usr/local/share/youtube_upload instead of /usr/share/youtube_upload. When youtube-upload runs, sys.prefix has a value of '/usr' and thus cannot find the default client_secrets.json. If you pass --install-layout=deb to the the install command, it will install in /usr/share (ie 'sudo python setup.py install --install-layout=deb'). Probably should document this option or modify the script so it correctly sets the default client_secrets location to /usr/local/share. Note that disttools is actually installing youtube-upload into /usr/local/bin and the youtube_upload python files to /usr/local/lib/python2.7/dist-packages/youtube_upload, so it seems like the correct thing would be to modify the default to use /usr/local/share.

**Comment by tokland** [comment]
Thanks for looking into it.

I wonder if checking (sys.prefix + "local" + FILEPATH) and then (sys.prefix + FILEPATH) makes sense.

**Comment by kldavis4** [comment]
Yes, I think checking both would fix the issue. I wish I could figure out why sys.prefix isn't returning '/usr/local' on debian/ubuntu, though.

**Comment by eg0r** [comment]
I found two bugs.

1. The file https://github.com/tokland/youtube-upload/blob/master/youtube_upload/auth/browser.py using the wrong import.
2. `auth` folder is not copied to the installation.

**Comment by tokland** [comment]
@eg0r please check! 50a3565

**Comment by eg0r** [comment]
@tokland in file https://github.com/tokland/youtube-upload/blob/master/youtube_upload/auth/browser.py need to use the import as follows:
```python
from youtube_upload import lib as lib
```

**Comment by tokland** [comment]
I don't get it. What's the difference between "from X import Y as Y" and "from X import Y"? works for me (python 2.7)

**Comment by eg0r** [comment]
This my fail.

**Comment by eg0r** [comment]
@tokland in file upload_video.py first two import not usage.

**Comment by tokland** [comment]
indeed! f6cb948

**Comment by tokland** [comment]
@kldavis4  check 9f7abce.

One should be able to do this cleanly with pkg_resources.resource_name, but this load from the lib directory, not the share. Any hints welcome, either the resources loading in Python is a mess or I simply don't get it.

http://stackoverflow.com/questions/14211575/any-python-function-to-get-data-files-root-directory
