### ISSUE TITLE
error: ImportError: No module named googleapiclient.errors

### ISSUE THREAD

**Issue by mxhub** [tokland/youtube-upload#186]
Hello,

i am getting this error. this is my first time using youtube-upload.
may i know what i could be doing wrongly?

```

Traceback (most recent call last):
  File "/usr/bin/youtube-upload", line 9, in <module>
    from youtube_upload import main
  File "/usr/lib/python2.6/site-packages/youtube_upload/main.py", line 24, in <module>
    import googleapiclient.errors
ImportError: No module named googleapiclient.errors

```

**Comment by Utty88** [comment]
As the Manual says, you have to install google-api-python-client to be able to use youtube-upload.

**Comment by mxhub** [comment]
i have figure out what went wrong.

i went to reinstall everything under python2.7 environment and it works now.

**Comment by AnanyaChandraker** [comment]
Try with below command, it worked for us:

pip install --upgrade google-api-python-client

It depends on the environment, I'm working with Python 3.6.5

**Comment by gevrey** [comment]
I have the same issue on Ubuntu 20.04 LTS
Installed google-api-python-client
`
Traceback (most recent call last):
  File "bin/youtube-upload", line 9, in <module>
    from youtube_upload import main
  File "/home/common/youtube-upload-master/bin/../youtube_upload/main.py", line 25, in <module>
    import googleapiclient.errors
ImportError: No module named googleapiclient.errors
`

**Comment by wellisrite** [comment]
Any solution for this yet? 
`Traceback (most recent call last):
  File "bin/youtube-upload", line 9, in <module>
    from youtube_upload import main    
  File "xx.py", line 25, in <module>
    import googleapiclient.errors
ImportError: No module named googleapiclient.errors`

**Comment by supervision** [comment]
Hi @mxhub,
how did you re-install?

I have the same issue (No module named googleapiclient.errors) on my MacOS 10.14 running Python 2.7.16.
Pip and pip3 are installed, but used pip3 for the initial install:

sudo pip3 install --upgrade google-api-python-client oauth2client progressbar2

after that, I installed pip - that might be my problem ...

**Comment by ehlen** [comment]
As noted above, either you haven't installed the google-api-python-client library, or, more likely, you installed it on a python distribution that is different from the one that's running the application. This is particularly likely to happen if you're running the installed script, as they show you in the instructions. Try this:

First, check where the script is running:

```$ which youtube-upload```

This will probably tell you the script is running in someplace "/usr/local/bin/youtube-upload". Whichever it is, crack that file open:

```$ vi /usr/local/bin/youtube-upload```

Now look at the shebang at the top line. It probably tells you the script is using the Python installation here:

``` #! /usr/bin/python ```

Now run that in the command line:

```$ /usr/bin/python```

Is this the distribution that you installed the google client API package for? Or did you install in using some Python 3.x and this gives you some 2.7 distribution? If so, that's your problem!

How to fix it?

Either: (1) Install the google api using the old distribution:

``` $ /usr/bin/python -m pip install google-api-python-client ```
 
Or: (2) Change the shebang in the script to run the distribution you prefer:

``` $ which python ```
``` $ vi /usr/local/bin/youtube-upload ```
```[change the first line to the output from "which python"] ```

**Comment by turkeyphant** [comment]
> As noted above, either you haven't installed the google-api-python-client library, or, more likely, you installed it on a python distribution that is different from the one that's running the application. This is particularly likely to happen if you're running the installed script, as they show you in the instructions. Try this:
> 
> First, check where the script is running:
> 
> `$ which youtube-upload`
> 
> This will probably tell you the script is running in someplace "/usr/local/bin/youtube-upload". Whichever it is, crack that file open:
> 
> `$ vi /usr/local/bin/youtube-upload`
> 
> Now look at the shebang at the top line. It probably tells you the script is using the Python installation here:
> 
> `#! /usr/bin/python`
> 
> Now run that in the command line:
> 
> `$ /usr/bin/python`
> 
> Is this the distribution that you installed the google client API package for? Or did you install in using some Python 3.x and this gives you some 2.7 distribution? If so, that's your problem!
> 
> How to fix it?
> 
> Either: (1) Install the google api using the old distribution:
> 
> `$ /usr/bin/python -m pip install google-api-python-client`
> 
> Or: (2) Change the shebang in the script to run the distribution you prefer:
> 
> `$ which python` `$ vi /usr/local/bin/youtube-upload` `[change the first line to the output from "which python"] `

thanks this is very helpful but doesn't work for me.

If I try (1) I get:
```
/usr/bin/python -m pip install google-api-python-client
/usr/bin/python: No module named pip
```
I can't try (2) because which python is already `/usr/bin/python` which is the same as the shebang in `/usr/bin/youtube-upload`
