### ISSUE TITLE
code 400: message": "The user has exceeded the number of videos they may upload."

### ISSUE THREAD

**Issue by mxhub** [tokland/youtube-upload#188]
Hello,

May i know how do we go about upload more videos or bypass this limit?

`[RequestError] Server response: {
 "error": {
  "errors": [
   {
    "domain": "youtube.video",
    "reason": "uploadLimitExceeded",
    "message": "The user has exceeded the number of videos they may upload."
   }
  ],
  "code": 400,
  "message": "The user has exceeded the number of videos they may upload."
 }
}
`

**Comment by sezeryalcin** [comment]
Why you don't ask youtube? It's clear this is not a bug of uploader script. So consider closing this ticket.

**Comment by mxhub** [comment]
there is a limit per user allow. closing this ticket

**Comment by fireflyso** [comment]
I get this code too,Do you have same idea for upload more video per day?
