### ISSUE TITLE
Very slow upload speed (chunk size related)

### ISSUE THREAD

**Issue by DavidVentura** [tokland/youtube-upload#19]
Hi
I suppose I have a high ping to youtube, the default 16\*1024 chunk size ends up with ~30kB/s uploaded. using 300\*1024 maxes up my upload at about 375kB/s
Maybe this should be a config ?

**Comment by tokland** [comment]
I left the small chunksize to have a nicer progressbar update rate, but it's slowing things too much. I'd prefer not to add an option for such tweaks. Set to 1024*1024. Does it work well for?  0b3abcad

**Comment by DavidVentura** [comment]
Thanks, I'll test it out.
Is there an option to set the video as unlisted, and also to disallow comments and ratings? If not I'll make a PR next week

**Comment by kldavis4** [comment]
I tried out this change and uploading a 210MB file went from 19 minutes to 20 seconds

**Comment by tokland** [comment]
Wow, then it makes a huge difference.

> Is there an option to set the video as unlisted

--privacy=unlisted

> and also to disallow comments and ratings?

Nope, PR welcomed!
