### ISSUE TITLE
Upload video longer than 1h

### ISSUE THREAD

**Issue by c0degeekPL** [tokland/youtube-upload#193]
Hi there. I have 1:36:00 movie and I would like to push them to YT using this script. I have a Youtube partnership account so I can upload the 128GB file. My movie's weight is 11GB.

Using this script the movie is cuted to 1:02:00 without any error. What can be wrong?

**Comment by ManuCart** [comment]
What's the error?
Try again it should work

**Comment by c0degeekPL** [comment]
Sorry - my bad! The file was corrupted o_O. Sorry again...

**Comment by avioli** [comment]
@c0degeekPL  you should close this issue then.
