### ISSUE TITLE
define license type

### ISSUE THREAD

**Issue by Django-BOfH** [tokland/youtube-upload#194]
How Is it possible to define the license-type "creative-commons by-sa"?

**Comment by mtcjayne** [comment]
This [change](https://github.com/mtcjayne/youtube-upload/commit/396647a2a21fc6e2a443f9f6cd6cee3ddf3041f8) would achieve that.

**Comment by kootsoop** [comment]
Closing as the ``--license`` option allows setting the license.

**Comment by patcon** [comment]
Thanks for reviving this project @kootsoop :)))

**Comment by kootsoop** [comment]
You're welcome @patcon !  Feel free to let me know what else needs doing. I'll need a bit of time to finish triaging the bug list, but it'd be nice to move it forward once that's mostly under control.
