### ISSUE TITLE
No module "googleapiclient.discovery"

### ISSUE THREAD

**Issue by binyominzeev** [tokland/youtube-upload#21]
After a fresh install on Ubuntu 14.04 I get this error when starting youtube-upload:

"ImportError: No module named apiclient.discovery"

I already tried to install several related packages, with no success so far.

Thank you!

**Comment by tokland** [comment]
Which related packages have you installed? This should be enough:

```
$sudo pip install --upgrade google-api-python-client
```

**Comment by binyominzeev** [comment]
Thank you, it works!

**Comment by tokland** [comment]
Great! Added a note on the readme.
