### ISSUE TITLE
Uploading a file outside the youtube-upload folder

### ISSUE THREAD

**Issue by rothlive** [tokland/youtube-upload#210]
Hello

i hope anyone can help me.
I want to upload a File but with fad specification.

youtube-upload --title="$(date "+%e-%b-%Y")" --privacy="private" /home/pi/$(date --date "-1 days" +'%e-%b-%Y').mp4

Works not.
I works only when i put the mp4 File into the install folder of youtube-upload.

**Comment by KenSharp** [comment]
`cd` to the directory first.

**Comment by rothlive** [comment]
Ok thanks
