### ISSUE TITLE
Dowsn't work with Windows 8

### ISSUE THREAD

**Issue by hakarune** [tokland/youtube-upload#22]
Tried using CMD and Powershell. I ran and installed dependencies and then install this and youtube-upload doesn't work. All I get is an error in PS, CMD, and Python. There are no instructions here for windows it seems :(.

PS:
```
youtube-upload : The term 'youtube-upload' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1

youtube-upload
--------------------------
CategoryInfo : ObjectNotFound: (youtube-upload:String) [], CommandNotFoundException
FullyQualifiedErrorId : CommandNotFoundException`
```

CMD:
```
'youtube-upload' is not recognized as an internal or external command, operable program or batch file.`
```

Py:
```
Traceback (most recent call last):
File "", line 1, in 
NameError: name 'youtube' is not defined
```

**Comment by hakarune** [comment]
Finally managed to not get an error, but it doesn't take me to create my credentials or anything. It just creates its own json with no auth to my account and doesn't upload.

**Comment by tokland** [comment]
Sorry, no Windows here to test. You can paste the command and the output, and see if some Windows user lends a hand.

**Comment by hakarune** [comment]
I enter the 'youtube-upload.py video.mp4'  and nothing outputs, it just go back to command prompt start

**Comment by tokland** [comment]
No output at all? No idea what may be happening, sorry.

**Comment by cyberjacob** [comment]
Windows doesn't recognise the python file, your best bet is to run something like `python main.py` from inside the youtube_upload folder

**Comment by rensa** [comment]
I'm having a similar problem on a Linux server. I've installed the package using `setup.py`, but I can't execute from the shell using the syntax provided:

    -bash: youtube-upload: command not found

I've also tried executing using `python youtube_upload/main.py [args]`, but I get:
```
Traceback (most recent call last):
  File "youtube_upload/main.py", line 25, in <module>
    import youtube_upload.auth
ImportError: No module named youtube_upload.auth
```

**Comment by tokland** [comment]
@rensa: Check the output of running setup.py to see where the youtube-upload executable is being installed. To run locally:

```
youtube-upload$ PYTHONPATH=. youtube_upload/main.py
```

**Comment by rensa** [comment]
@tokland: Would that method of running locally still work if I was running a Python virtual environment?

**Comment by tokland** [comment]
Create file YOUR_ENV/lib/python2.7/site-packages/youtube-upload.pth with a single line, the absolute path of the root of the youtube-upload code. Then run ```python youtube_upload/main.py```
