### ISSUE TITLE
youtube-upload failed ImportError

### ISSUE THREAD

**Issue by imnavas** [tokland/youtube-upload#221]
youtube-upload fails

$ youtube-upload
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 9, in <module>
    from youtube_upload import main
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 24, in <module>
    import googleapiclient.errors
ImportError: No module named googleapiclient.errors

**Comment by mostyy** [comment]
I get same error on Python3 Env and I think it is not run on Python 3.4.

**Comment by rothlive** [comment]
Install :
sudo apt-get install python-pip 
sudo pip install --upgrade google-api-python-client progressbar2

**Comment by imnavas** [comment]
**Installed pip:**
$ sudo apt-get install python-pip
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-pip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 423 not upgraded.

**Installed depends:**
$ sudo -H pip install --upgrade google-api-python-client progressbar2
Requirement already up-to-date: google-api-python-client in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: progressbar2 in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: oauth2client<5.0.0dev,>=1.5.0 in /usr/local/lib/python3.4/dist-packages (from google-api-python-client)
Requirement already up-to-date: six<2dev,>=1.6.1 in /usr/local/lib/python3.4/dist-packages (from google-api-python-client)
Requirement already up-to-date: httplib2<1dev,>=0.9.2 in /usr/local/lib/python3.4/dist-packages (from google-api-python-client)
Requirement already up-to-date: uritemplate<4dev,>=3.0.0 in /usr/local/lib/python3.4/dist-packages (from google-api-python-client)
Requirement already up-to-date: python-utils>=2.3.0 in /usr/local/lib/python3.4/dist-packages (from progressbar2)
Requirement already up-to-date: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.4/dist-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client)
Requirement already up-to-date: pyasn1>=0.1.7 in /usr/local/lib/python3.4/dist-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client)
Requirement already up-to-date: rsa>=3.1.4 in /usr/local/lib/python3.4/dist-packages (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client)

**Version of python:**
$python -V
Python 2.7.12

**Version of ubuntu**
$ cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

**youtube-upload failed :-(**
~/src/youtube-upload-master$ export PYTHONPATH=.;python bin/youtube-upload
Traceback (most recent call last):
  File "bin/youtube-upload", line 9, in <module>
    from youtube_upload import main
  File "/home/ibu/src/youtube-upload-master/bin/../youtube_upload/main.py", line 24, in <module>
    import googleapiclient.errors
ImportError: No module named googleapiclient.errors

**Comment by rothlive** [comment]
Ok then i can not help Sorry. I use it on Debian on a Raspberry.
