### ISSUE TITLE
Putting out a Call For Maintainers?

### ISSUE THREAD

**Issue by patcon** [tokland/youtube-upload#224]
Hey @tokland! Thanks so much for this project :)

Seems like you might be a little busy lately, as there hasn't been a merge since last May.

If I went through the commit history to find some past contributors who've already submitted pull requests, might you be willing to give push access to those who are willing to do some triage and feature testing? I imagine after that, this could just involve a little strategizing around expectations for testing/triage/merging/etc, and maybe putting that into a CONTRIBUTING.md file?

(You would obviously get last call on who gets push access, but I'm just offering to do the leg-work of organizing it :) )

**Comment by tokland** [comment]
The answer is: by all means, thank you!  :)

**Comment by patcon** [comment]
Woooo! Thanks @tokland 

Hey @coddingtonbear, might you be interested? :) You seem pretty active on github, and you're already actively maintaining a python package, [`django-mailbox`](https://github.com/coddingtonbear/django-mailbox)

I know it's been awhile since your one and only contrib, but might you be down to help tend the issue queue or merge some PRs?

**Comment by patcon** [comment]
What about you, @andir? you weren't around this repo a whole lot, but you're still really active on github, and seems like you use python for ops stuff. Do you still use this project? And regardless, might you be interested in helping unstick things a bit? (issues or code or docs or whatevs works for you!)

**Comment by andir** [comment]
I am probably not the best pick for this.. I've not been using the tool since my last contributions.

I can probably be one of many people to review new PRs but not a good SPOF ;-)

**Comment by patcon** [comment]
thx for quick response and candidness! haha SPOF is prob where we are now. maybe we can all be nodes in a MPOF system :)

**Comment by coddingtonbear** [comment]
I really appreciate the invitation, @patcon, but I'm afraid I'm already unable to devote the necessary time to maintain the projects I currently look after.  I would like to say, though, that I think it's really great for you to try to find maintainers for projects like this in the way you are here.  Good luck on your hunt for help!
