### ISSUE TITLE
How do you uninstall?

### ISSUE THREAD

**Issue by uzelessknowledge** [tokland/youtube-upload#225]
Once this is installed how do you uninstall it?
I saw it authenticate, but don't know that it was under my account. Is it using your API key?

**Comment by kootsoop** [comment]
[This gives an example.](https://stackoverflow.com/a/25209129/12570)

For Unix-like:

```
    sudo python setup.py install --record files.txt
    # inspect files.txt to make sure it looks ok. Then:
    tr '\n' '\0' < files.txt | xargs -0 sudo rm -f --
```
