### ISSUE TITLE
Monetization option

### ISSUE THREAD

**Issue by QurQuma** [tokland/youtube-upload#227]
Hi,
  is there a way I can specify on/off for video monetization?
Thanks,
Francesco

**Comment by zielinsm** [comment]
Unfortunately, you can't. YouTube's API _videos.insert_ method has no parameter that would enable users to specify if they want their video to be monetized or not.

**Comment by QurQuma** [comment]
Ok, thanks!

**Comment by RoelVdP** [comment]
See #199
