### ISSUE TITLE
Getting "Retryable Error" permanently since today

### ISSUE THREAD

**Issue by DavidVentura** [tokland/youtube-upload#23]
Hi
I've been using this twice a week to upload videos and today it decided to stop working. I cloned git master and it's the same thing. I'm thinking this has to be on youtube's side.
No matter what video I choose to upload I get this:

```
Using client secrets: /usr/share/youtube_upload/client_secrets.json
Using credentials file: /home/david/.youtube-upload-credentials.json
Start upload: tratcompleto1.mp4 (aaaaaa)
Retryable error 1/10: ResumableUploadError. Waiting 0.0655516964213 seconds
Retryable error 2/10: ResumableUploadError. Waiting 1.42532378912 seconds
Retryable error 3/10: ResumableUploadError. Waiting 2.97410480509 seconds
Retryable error 4/10: ResumableUploadError. Waiting 6.27177218128 seconds
Retryable error 5/10: ResumableUploadError. Waiting 28.9982075691 seconds
```

I deleted and re-created my credentials, it's the same thing. Same with privacy/no privacy

**Comment by DavidVentura** [comment]
Ok so I'm getting 
```
<HttpError 403 "Daily Limit Exceeded">
```
as the error; I've set up an oauth key (service) but it does not have the same keys/values that the default credentials json file has. What did I do wrong?

**Comment by DavidVentura** [comment]
So it seems like I have to use an "Application" key, stored as the client secrets, delete the credentials file, re-create it with the program, and then it works. Maybe you could add this to the readme?

**Comment by tokland** [comment]
This should be in the docs, indeed. Check the changes in the readme.
