### ISSUE TITLE
--description="Test" seems to be ignored

### ISSUE THREAD

**Issue by ajcraig99** [tokland/youtube-upload#232]
I have the description arg just set to some test text yet my uploads do not end up with any description.
The title and privacy setting works as expected.
Have I written it wrong or can you see anything I have done incorrectly below?

`youtube-upload --title="Timelapse_$filename" --description="Test" --privacy public 
 /home/pi/timelapse/video/$filename.avi`

**Comment by ajcraig99** [comment]
Solved,.......but i don't know how.

I just re-wrote my script and it's working now haha

**Comment by kootsoop** [comment]
This works for me.  You'll need to give more information if it's still a problem.
