### ISSUE TITLE
how to use chinese title?

### ISSUE THREAD

**Issue by kxltsuper** [tokland/youtube-upload#236]
when i use :   youtube-upload --title="好好学习" out.mp4, it throws an error.
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 4: ordinal not in range.
how can i use chinese title?

python2.7 ,  CentOS6

**Comment by AndCycle** [comment]
watch out your environment variable,
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```
and use python3 as py2 you needs to handle tons of non-unicode issue.

**Comment by kootsoop** [comment]
Closing as AndCycle's suggestion seems to fix issue.
