### ISSUE TITLE
Disable comment

### ISSUE THREAD

**Issue by skeith** [tokland/youtube-upload#240]
Is there any metadata to be passed to disable comment on uploaded video using youtube-upload?

**Comment by avibrazil** [comment]
I'm also interested in this. Specially for the command (in addition to the API implementation)

**Comment by avibrazil** [comment]
Apparently this is a known YouTube v3 API issue since at least 2015:

https://stackoverflow.com/a/29463431

**Comment by ZainRizvi** [comment]
This issue seems like it can be closed since it can't be fixed

**Comment by kootsoop** [comment]
Closing, as it's a Google API issue.
