### ISSUE TITLE
No module named oauth2client

### ISSUE THREAD

**Issue by ludovicsclain** [tokland/youtube-upload#242]
Hi!
When I upload my video with a call like : 
`$ youtube-upload --title="A.S. Mutter" --auth-browser anne_sophie_mutter.flv`

I have an error : 
`Traceback (most recent call last):
File "/usr/bin/youtube-upload", line 9, in <module> from youtube_upload import main
File "/usr/lib/python2.7/site-packages/youtube_upload/main.py", line 25, in <module> import oauth2client
ImportError: No module named oauth2client`

Any help please?
Regards,
Ludovic

**Comment by evertonstz** [comment]
Install oauth2client with pip: sudo pip install oauth2client

The owner already updated the readme.

**Comment by kootsoop** [comment]
I believe this is fixed now.
