### ISSUE TITLE
[ Solved] Error: disabled_client

### ISSUE THREAD

**Issue by pekseg** [tokland/youtube-upload#247]
I'm using the video upload automatized (daily based) from two servers. Since yesterday both stopped to work.  I got an error 401, error: disabled client

![image](https://user-images.githubusercontent.com/177244/44653007-d1fa8680-a9ed-11e8-8f06-9ca9df05d7b9.png)

I checked the console, the API seems to be fine, tried to regenerate new client id, but didn't help.

**Comment by paolo-italy** [comment]
The same here. I updated google API client libs but nothing works.

**Comment by MCOfficer** [comment]
it seems that this project's oauth2 application got disabled. for now, you can create and use your own application, as described in the [README](https://github.com/tokland/youtube-upload#authentication)

**Comment by asperduti** [comment]
@MCOfficer  That is not the solution. I have my own project.

**Comment by MCOfficer** [comment]
it was working for me. i created a new application to check, and ran into the same issue. i resolved it by
a) setting an E-Mail adress in the [OAuth Consent Screen Settings](https://console.developers.google.com/apis/credentials/consent)
b) setting a product name in the same settings
c) making sure client name, application name and product name are one and the same.

**Comment by pekseg** [comment]
hmmm, I provided now a client_secret file, and it works... strange how this has been working sofar.
Thanks for the tip. I'm closing this ticket.

**Comment by paolo-italy** [comment]
No way, I tried creating even a new Gmail account, new credentials, but I cannot obtain the verification code, with error 401.
