### ISSUE TITLE
disabled_client

### ISSUE THREAD

**Issue by paolo-italy** [tokland/youtube-upload#248]
Issue #247 has not been solved for me.

I have three accounts, and no one is working starting from yesterday. In just one case I get an error accessing .youtube-upload-credentials.json file (???); for both the other ones I cannot obtain a new verification code from the browser, with error 401 - disabled_client.
I tried onto two different clients, with different IPs. 
Tried to create a new client ID for each account, but no way; tried a new Gmail account also.

My production account is a GSuite one, but it is not working at all. 

Any help?

Regards 

Paolo

**Comment by pekseg** [comment]
are you using client-secrets? if no, goto google console, download the oauth2 client id (json) and pass this as parameter (--client-secrets).

**Comment by paolo-italy** [comment]
Yes, I am using my own credentials since 2016. 

PZ
Inviato da iPhone

**Comment by DavidVentura** [comment]
Same here

**Comment by DavidVentura** [comment]
Solved by following pekseg's idea anyway: I created and downloaded a new secret. I hope this one also lasts 2 years

**Comment by bees4ever** [comment]
Same here, I will try @pekseg 's idea, but this answer from google is very strange

**Comment by tokland** [comment]
Sorry for the delay, I got no notification. 

It's simple: Google has revoked the credentials with a "Policy violation" So now every user must create and use its own json secrets file. I'll update the README.
