### ISSUE TITLE
Warn user if title > 100 chars

### ISSUE THREAD

**Issue by lasconic** [tokland/youtube-upload#25]
Apparently youtube doesn't accept video upload with title > 100chars. Currently, youtube-upload fails with

Retryable error 1/10: ResumableUploadError. Waiting 0.666298561664 seconds 

The message could be more explicit.

**Comment by tokland** [comment]
Indeed, it should be more descriptive (and non-retryable). I'll look into
it.

--- From mobile

**Comment by MaxCodeX** [comment]
@tokland, you can substr from title input to 100 character from source. Therefore, everybody can avoid this exception
or 
@lasconic substr to 100 character before use youtube-upload

This issue same for title, des, tag

You can go to https://www.youtube.com/upload and upload a video to test

I remember, title.length <= 100, des.length <= 5000, tag.length <= 500

**Comment by tokland** [comment]
Show server errors: 4b13608c
