### ISSUE TITLE
No longer working, 'youtubeSignupRequired'?

### ISSUE THREAD

**Issue by musubk** [tokland/youtube-upload#251]
Has google changed something in the last week that broke this utility? Or is it just me that's suddenly having problems? I've been using this for around 2 years now to upload videos from an automated camera system, with a little under 700 videos uploaded so far. About a week ago it just stopped working, and now gives me an error message:
code: 401
message: Unauthorized
reason: youTubeSignupRequired
I've been googling this error message and everything suggests it happens if you try to upload using credentials generated by a google account with no associated YouTube account. But I have an associated YouTube account - two actually - and I've successfully uploaded to it many times before. I've tried generating a new client_secrets file and I've tried reinstalling the youtube-upload utility but the problem remains. Any insight as to what the problem might be?

**Comment by tokland** [comment]
Yes, Google revoked the private key what shipped with the package. However, it should work with your own secrets file. Latest youtube-upload version reads it automatically from `~/client_secrets.json` (the download file was `client_id.json`). Paste the full output of a failing command.

**Comment by musubk** [comment]
Okay, I've got myself authenticated again using a new client_secrets file. Now I'm getting this error when I attempt an upload:

Using client secrets: /usr/share/youtube_upload/client_secrets.json
Using credentials file: /home/jason/.youtube-upload-credentials.json
Traceback (most recent call last):
  File "/usr/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/lib/python3.6/site-packages/youtube_upload/main.py", line 448, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/lib/python3.6/site-packages/youtube_upload/lib.py", line 42, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/youtube_upload/main.py", line 441, in main
    run_main(parser, options, args)
  File "/usr/lib/python3.6/site-packages/youtube_upload/main.py", line 312, in run_main
    if options.caption_file.lower() in ["auto", "a"]:
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by musubk** [comment]
Ah, I think I may have introduced this problem when I was playing with the [captions/subtitles support fork](https://github.com/evertonstz/youtube-upload), then deleted it (so I thought) and moved back to this one...

**Comment by tokland** [comment]
Yup, this code is not in this fork.

**Comment by musubk** [comment]
Yes, I've moved back to your fork for real this time, and it's working now with my new client_secrets file. Thanks for your help.
