### ISSUE TITLE
how can I check upload progress?

### ISSUE THREAD

**Issue by zzm88** [tokland/youtube-upload#252]
it shows Start upload: 12a3db1dc9bf4db3b5e4a2fa4ee80c3f.mp4
and sticks for a few minutes. 
How to tell if it is uploading or just being stuck?

**Comment by tokland** [comment]
Is package `progressbar2` installed? If so, try setting the chunk size option, for example: `--chunksize=1024000`

**Comment by kootsoop** [comment]
No feedback from @tokland 's comment, so closing.
