### ISSUE TITLE
Blocking batch commands from running

### ISSUE THREAD

**Issue by bilfr3d** [tokland/youtube-upload#256]
Suppose I have a batch file like the following, to upload some videos:

```
@echo off
youtube-upload --title="test" test.mp4
del test.mp4
exit
```

If I call this batch file like `start test.bat`, it will spawn the new window, run youtube-upload and upload the video, but will then just drop back into a console mode without ever running the remaining commands. This happens regardless the commands placed after youtube-upload, even other youtube-uploads do not run in the same batch file.

Windows 10

**Comment by kootsoop** [comment]
Works for me.
