### ISSUE TITLE
Retryable error x/10: ResumableUploadError

### ISSUE THREAD

**Issue by mfraser** [tokland/youtube-upload#26]
Trying to upload a video
youtube-upload --category="Short Movies" --title="Timelapse 150515"  /mnt/video/Timelapse/timelapse-150515.mp4
All I get is 
Retryable error 1/10: ResumableUploadError. Waiting 1.04799341928 seconds
Retryable error 2/10: ResumableUploadError. Waiting 0.998596183914 seconds
Retryable error 3/10: ResumableUploadError. Waiting 6.92854485734 seconds
Retryable error 4/10: ResumableUploadError. Waiting 2.02846262772 seconds
Retryable error 5/10: ResumableUploadError. Waiting 5.41348200998 seconds
Retryable error 6/10: ResumableUploadError. Waiting 15.2127477185 seconds
Retryable error 7/10: ResumableUploadError. Waiting 50.0016125671 seconds
...
Retryable error 10.10;

Nothing gets uploaded.

**Comment by mfraser** [comment]
googleapiclient.errors.ResumableUploadError: <HttpError 400 "Bad Request">

**Comment by lasconic** [comment]
I'm just a new user but it seems ResumableUploadError is used for a bit everything. Maybe you could try without the category?

**Comment by tokland** [comment]
I get the same error with that category. "Short Movies" is an existing category (at least region US) for but for some reason it does not work. Check https://developers.google.com/youtube/v3/docs/videoCategories/list (part=snippet + regionCode + Execute)

Added a more detailed exception message: 19757cfc

**Comment by tokland** [comment]
This should the exact error: 4b13608c

No idea why the category is not accepted, but it's a server-side thing.
