### ISSUE TITLE
Youtube Quota Exceeded Exception when it's actually not

### ISSUE THREAD

**Issue by Jaqen00** [tokland/youtube-upload#268]
I'm using  youtube-upload and have been for quite some time without any problems. Recently, we've been getting this 403 exception:

Using client secrets: /root/ytb_api/ppx_client_secrets.json
Using credentials file: /root/ytb_api/ppx_credentials.json
Start upload: ./ppx_video/new.mp4
[RequestError] Server response: {
 "error": {
  "errors": [
   {
    "domain": "youtube.quota",
    "reason": "quotaExceeded",
    "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e."
   }
  ],
  "code": 403,
  "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e."
 }
}

In the google developer's console, it says that we are still under the quota (currently it states "units/day 163,817 of 50,000,000").
Am I missing something about how it work?

**Comment by Jaqen00** [comment]
@tokland

**Comment by bichotll** [comment]
Unfortunately, Youtube has drastically reduced the quota to 10.000 per day for any new/recently created API.

**Comment by AndCycle** [comment]
not just recently, the secret key from my old project is no longer usable, they have roll out the quota limit to everyone.

**Comment by bichotll** [comment]
> not just recently, the secret key from my old project is no longer usable, they have roll out the quota limit to everyone.

That did not happen to me. I have a key that is ± a year old?

For the record. There is a form to request more quota: https://services.google.com/fb/forms/ytapiquotarequest/

**Comment by AndCycle** [comment]
have read the official document
https://developers.google.com/youtube/v3/getting-started#quota

```Note that projects that had enabled the YouTube Data API before April 20, 2016, have a different default quota for that API.```

although the statement says it only affect project after 2016, 
one of my old project created at 2012 is affected and got weird issue prevent it from using youtube data api.

**Comment by bichotll** [comment]
Ugh...Youtube is becoming too restrictive - and messy!
I hope there is a change soon..or a new video platform!

**Comment by indatawetrust** [comment]
I was having this issue with a newly opened google cloud account. I didn't experience this problem when I tried it from another account that was actively used and had a billing.

**Comment by Jaqen00** [comment]
I‘m using selenium for a alternative way to upload more videos

**Comment by renenijman** [comment]
> I‘m using selenium for a alternative way to upload more videos

Could you elaborate? I cannot seem to find how to do that.

**Comment by Jaqen00** [comment]
use chrome webdriver，find the <input name=“file”> element and sendfile.@renenijman

**Comment by renenijman** [comment]
> use chrome webdriver，first login Google account in webdriver,then find the <input type=“file”> element in upload page and sendfile.@renenijman

Got it. Thanks for the quick reply!

**Comment by ShuhuaGao** [comment]
@Jaqen00  Is there any limit on the number of videos if we use selenium?

**Comment by Jaqen00** [comment]
Yes，there is a frequency limit。but it is enough  for me

Shuhua Gao <notifications@github.com>于2019年5月18日 周六上午11:32写道：

**Comment by ShuhuaGao** [comment]
@Jaqen00 Thank you for the quick response. That would be great without such strict quota limitation. I encountered some weird issues with YouTube Data API V3: even with a newly created project on Google Console and its secrets file, it shows 'quota exceeded' when uploading video with this 'youtube-upload' tool.

**Comment by emughal85** [comment]
is there any kind of search limit in youtube data API V3 of quota?

**Comment by suneetk92** [comment]
> 
> 
> is there any kind of search limit in youtube data API V3 of quota? Like 100 searches i can do in a day or more than this can anyone tell me?

YouTube Search API consumes 100 units and the quota limits is set to 10,000. So,
`no of searches = 10,000/100 = 100 searches`

**Comment by tavurth** [comment]
Quota is 1,600 per video upload. This still works for me, as I can get around 6 videos per day uploaded. Some days I have more videos than others, but I can just queue them up with a cron to be uploaded on a day with less traffic.

If you really need more, you can also pay to increase the quota up as high as you want.

**Comment by brokeharvard** [comment]
> use chrome webdriver，first login Google account in webdriver,then find the <input type=“file”> element in upload page and sendfile.@renenijman

@Jaqen00 Any chance you could share your code for doing this? Were you able to insert video title, description, tags, custom thumbnail, etc?

**Comment by linouk23** [comment]
> use chrome webdriver，first login Google account in webdriver,then find the element in upload page and sendfile.@renenijman
> @Jaqen00 Any chance you could share your code for doing this?
@brokeharvard 

Please check out https://github.com/linouk23/youtube_uploader_selenium.

**Comment by moiseyo** [comment]
I have Quota Name Limit  Queries per day 0 

##############################################################

youtube.error.PyYouTubeException: YouTubeException(status_code=403,message=The request cannot be completed 
because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.)

When I check  Quotas I saw :
-----------------------------------------
Quota Name Limit
Queries per day 	0 	
Queries per 100 seconds per user 	300,000 	
Queries per 100 seconds	3,000,000 	
---------------------------------------------
Errors  100 
YouTube Data API v3	12	100	51	367

**Comment by amnonbb** [comment]
I solve it by creating new project with new Credentials in Google Console.

**Comment by Jaqen00** [comment]
```
# -*- coding:utf-8 -*-
from selenium import webdriver
import re, time

driver = webdriver.Chrome()


def check_alert():  # if there is unsaved content ,you have to confirm a alert before leaving the current page
    try:
        driver.switch_to.alert.accept()
    except Exception as e:
        pass


def send_file(file_name):
    driver.find_element_by_id('create-icon').click()
    driver.find_element_by_css_selector('paper-listbox > paper-item').click()
    time.sleep(1)
    driver.find_element_by_css_selector('input[name="Filedata"]').send_keys(file_name)


def send_title(title):
    title_e = driver.find_element_by_id('textbox')
    for i in range(5):  # Make sure the text in 'title_e' is empty
        t_inside = title_e.text
        if t_inside:
            title_e.clear()
            time.sleep(1)
        else:
            break
    title_e.send_keys(title[0:95])  # There is a limit to the maximum length of title


def send_des(des):
    driver.find_element_by_class_name('description-textarea').find_element_by_css_selector(
        'div#textbox').send_keys(des[0:4800])  # There is a limit to the maximum length of des


def send_cover(cover):
    js = "var q=document.getElementById('dialog').scrollTop=500"
    driver.execute_script(js)
    time.sleep(1)
    driver.find_element_by_xpath('//*[@id="file-loader"]').send_keys(cover)
    print('send cover success')


def send_tags(tags):
    target = driver.find_element_by_xpath('//*[@id="details"]/div/div/ytcp-button/div')
    driver.execute_script("arguments[0].scrollIntoView();", target)
    target.click()
    time.sleep(1)
    target = driver.find_element_by_xpath(
        '//*[@id="tags-container"]/div[1]/div[2]/ytcp-free-text-chip-bar/ytcp-chip-bar/div/input')
    driver.execute_script("arguments[0].scrollIntoView();", target)
    time.sleep(1)
    target.send_keys(','.join(tags) + ',')


def click_next_step():
    driver.find_element_by_id('next-button').click()


def try_monetization_page(
        is_monetize):  # if you get monetized on Youtube,there is a additional page for monetization details
    if 'Choose how you want to earn money from your video' not in driver.page_source:  #To make sure you have monetized your channel
        return
    try:
        if is_monetize:
            driver.find_element_by_id('text-container').click()
            time.sleep(1)
            driver.find_element_by_id('radio-on').click()
            driver.find_element_by_id('save-button').click()
        driver.find_element_by_id('next-button').click()
    except:
        pass


def click_publish_confirm():
    try:
        driver.find_element_by_id('publish-button').click()
        time.sleep(3)
    except:
        pass


def upload(file_name='./example.mp4',
           title='title',
           des='description',
           cover='./example_cover.png',
           tags=['tag1,tag2'],
           is_monetize=True,  # set True to monetize your video
           is_public=True,  # set True to make your video 'public',or 'unlist'
           ):
    upload_url = 'https://studio.youtube.com'
    check_alert()
    all_handles = driver.window_handles
    for i in range(1, len(all_handles)):
        driver.switch_to.window(all_handles[i])
        driver.close()
        check_alert()
    driver.switch_to.window(all_handles[0])
    driver.get(upload_url)
    check_alert()
    time.sleep(3)
    send_file(file_name)
    time.sleep(5)
    send_title(title)
    send_des(des)
    time.sleep(2)
    if cover:
        send_cover(cover)
    time.sleep(1)
    if tags:
        send_tags(tags)
    click_next_step()
    try_monetization_page(is_monetize)
    # set_endscreen()
    click_next_step()
    time.sleep(1)
    if not is_public:
        driver.find_element_by_xpath('//*[@id="privacy-radios"]/paper-radio-button[2]').click()
    else:
        driver.find_element_by_xpath('//*[@id="privacy-radios"]/paper-radio-button[3]').click()
    i = 0
    while True:
        i += 1
        if i > 20:
            break
        progress = \
            re.findall(
                'ytcp-video-upload-progress">(\D{0,10}\d*%\D{0,10}|Finished processing|\D{0,10}complete\D{0,30})</span>',
                driver.page_source)
        print("upload mes:", progress)
        if not progress:
            time.sleep(2)
            continue
        progress = progress[0]
        if 'processed' in progress or "100%" in progress or 'Finished' in progress or 'complete' in progress:
            driver.find_element_by_xpath('//*[@id="done-button"]').click()
            time.sleep(5)
            if is_monetize:
                click_publish_confirm()
            return "success"
        time.sleep(2)
    return "upload failed"

```

This is my code to upload using selenium

**Comment by Jaqen00** [comment]
Share the code to upload using selenium:
Google forbids using automated scripts for logging into YTB now. So I use cookies for an alternative way.

Step 1:
1.launch chrome the following way to open a remote debugging port at 9222 port
`chrome.exe --remote-debugging-port=9222`
Or simply append the flag directly within the program properties by right-clicking on the Chrome icon and adding `--remote-debugging-port=9222`
![image](https://user-images.githubusercontent.com/27007870/100958345-1ffc7e00-3557-11eb-90ae-a8ccfd717537.png)
2.Login Google account manually.
3.Run the script to store the cookies:
```from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import json,time,re
chrome_options = Options()
chrome_options.add_experimental_option("debuggerAddress", "127.0.0.1:9999")
driver = webdriver.Chrome(chrome_options=chrome_options)
driver.get("https://www.google.com/")
user = re.findall('<div class="gb_rb">(.*?)@gmail.com</div>',driver.page_source)[0]
print('user:',user)
driver.get("https://www.youtube.com/")
time.sleep(3)
with open('./cookies/' + user + '.txt','w') as f:
    f.write(json.dumps(driver.get_cookies()))
print(json.dumps(driver.get_cookies()))
driver.quit()
```
Step 2:
Use the following functions to upload:
```# -*- coding:utf-8 -*-
from selenium import webdriver
import re, time,os,json

driver = webdriver.Chrome()


def set_cookies(cookie_file):
    if not os.path.exists(cookie_file):
        print("cookie file not exsit")
        return False
    driver.get("https://www.youtube.com")
    driver.delete_all_cookies()
    try:
        with open(cookie_file, "r") as fp:
            cookies = json.loads(fp.read())
        for cookie in cookies:
            if cookie.get("expiry"):
                cookie["expiry"] = int(cookie["expiry"])
            driver.add_cookie(cookie)
        driver.get("https://www.youtube.com")
        time.sleep(1)
    except:
        return False
    
    
def check_alert():  # Check if any alert exists
    try:
        driver.switch_to.alert.accept()
    except Exception as e:
        pass


def send_file(file_name):
    driver.find_element_by_id('create-icon').click()
    driver.find_element_by_css_selector('paper-listbox > paper-item').click()
    time.sleep(1)
    driver.find_element_by_css_selector('input[name="Filedata"]').send_keys(file_name)


def send_title(title):
    title_e = driver.find_element_by_id('textbox')
    for i in range(5):  # Make sure the input element of title is empty
        t_inside = title_e.text
        if t_inside:
            title_e.clear()
            time.sleep(1)
        else:
            break
    title_e.send_keys(title[0:95])  # There is a maximum title length


def send_des(des):
    driver.find_element_by_class_name('description-textarea').find_element_by_css_selector(
        'div#textbox').send_keys(des[0:4800])  # There is a maximum descrption length


def send_cover(cover):
    js = "var q=document.getElementById('dialog').scrollTop=500"
    driver.execute_script(js)
    time.sleep(1)
    driver.find_element_by_xpath('//*[@id="file-loader"]').send_keys(cover)
    print('send cover success')


def send_tags(tags):
    target = driver.find_element_by_xpath('//*[@id="details"]/div/div/ytcp-button/div')
    driver.execute_script("arguments[0].scrollIntoView();", target)
    target.click()
    time.sleep(1)
    target = driver.find_element_by_xpath(
        '//*[@id="tags-container"]/div[1]/div[2]/ytcp-free-text-chip-bar/ytcp-chip-bar/div/input')
    driver.execute_script("arguments[0].scrollIntoView();", target)
    time.sleep(1)
    target.send_keys(','.join(tags) + ',')


def click_next_step():
    driver.find_element_by_id('next-button').click()


def try_monetization_page(
        is_monetize):  # if you get monetized on Youtube,there is a additional page for monetization details
    if 'Choose how you want to earn money from your video' not in driver.page_source:  # make sure you have monetized your channel
        return
    try:
        if is_monetize:
            driver.find_element_by_id('text-container').click()
            time.sleep(1)
            driver.find_element_by_id('radio-on').click()
            driver.find_element_by_id('save-button').click()
        driver.find_element_by_id('next-button').click()
    except:
        pass


def click_publish_confirm():#if you choose to monetize your video before monetization check, there is a confirmation button 
    try:
        driver.find_element_by_id('publish-button').click()
        time.sleep(3)
    except:
        pass


def upload(cookie_file='./example.txt',
           file_name='./example.mp4',
           title='title',
           des='description',
           cover='./example_cover.png',
           tags=['tag1,tag2'],
           is_monetize=True,  # set True to monetize your video
           is_public=True,  # set True to make your video 'public',or 'unlist'
           ):
    set_cookies(cookie_file)
    upload_url = 'https://studio.youtube.com'
    check_alert()
    all_handles = driver.window_handles
    for i in range(1, len(all_handles)):
        driver.switch_to.window(all_handles[i])
        driver.close()
        check_alert()
    driver.switch_to.window(all_handles[0])
    driver.get(upload_url)
    check_alert()
    time.sleep(3)
    send_file(file_name)
    time.sleep(5)
    send_title(title)
    send_des(des)
    time.sleep(2)
    if cover:
        send_cover(cover)
    time.sleep(1)
    if tags:
        send_tags(tags)
    click_next_step()
    try_monetization_page(is_monetize)
    # set_endscreen()
    click_next_step()
    time.sleep(1)
    if not is_public:
        driver.find_element_by_xpath('//*[@id="privacy-radios"]/paper-radio-button[2]').click()
    else:
        driver.find_element_by_xpath('//*[@id="privacy-radios"]/paper-radio-button[3]').click()
    i = 0
    while True:
        i += 1
        if i > 20:
            break
        progress = \
            re.findall(
                'ytcp-video-upload-progress">(\D{0,10}\d*%\D{0,10}|Finished processing|\D{0,10}complete\D{0,30})</span>',
                driver.page_source)
        print("upload mes:", progress)
        if not progress:
            time.sleep(2)
            continue
        progress = progress[0]
        if 'processed' in progress or "100%" in progress or 'Finished' in progress or 'complete' in progress:
            driver.find_element_by_xpath('//*[@id="done-button"]').click()
            time.sleep(5)
            if is_monetize:
                click_publish_confirm()
            return "upload success"
        time.sleep(2)
    return "upload failed"

```

**Comment by Brainard-tech** [comment]
I'm using youtube-upload and have been for quite some time without any problems. Recently, we've been getting this 403 exception:

Using client secrets: /root/ytb_api/ppx_client_secrets.json
Using credentials file: /root/ytb_api/ppx_credentials.json
Start upload: ./ppx_video/new.mp4
[RequestError] Server response: {
"error": {
"errors": [
{
"domain": "youtube.quota",
"reason": "quotaExceeded",
"message": "The request cannot be completed because you have exceeded your \u003ca href="/youtube/v3/getting-started#quota"\u003equota\u003c/a\u003e."
}
],
"code": 403,
"message": "The request cannot be completed because you have exceeded your \u003ca href="/youtube/v3/getting-started#quota"\u003equota\u003c/a\u003e."
}
}

can anyone tell me what is happen because it wasn't quite long i started the project and having this problem
can

**Comment by AndCycle** [comment]
@Brainard-tech #313
