### ISSUE TITLE
Youtube API data v3: the quota is just 10,000 queries per day

### ISSUE THREAD

**Issue by JookiTsui** [tokland/youtube-upload#270]

**Comment by AndCycle** [comment]
don't know why you post this here, there is no workaround for this, the only way you can raise qutoa is by asking google from their support form.

**Comment by pfgp** [comment]
Just to add on: uploads cost 1607 credits. So that works out to be 6 uploads unless you request to have your quota raised.

**Comment by Jaqen00** [comment]
You can use selenium to upload more videos

**Comment by ZainRizvi** [comment]
This issue seems like it can be closed

**Comment by skeith** [comment]
can't we circumvent this by making (say) 10 projects, thus 10 client secrets rotated to get 100K units per day?

**Comment by eikichi87** [comment]
> 
> 
> Can't we circumvent this by making (say) 10 projects, thus 10 client secrets rotated to get more upload quota.
> 
> Based my rough calculation, with 10K units, you can only upload 6 videos

you cant just open like 15 projects and use them for uploading, google detects those very fast, and terminates your google account!

**Comment by skeith** [comment]
> > Can't we circumvent this by making (say) 10 projects, thus 10 client secrets rotated to get more upload quota.
> > Based my rough calculation, with 10K units, you can only upload 6 videos
> 
> you cant just open like 15 projects and use them for uploading, google detects those very fast, and terminates your google account!

yeah, was just an idea
but I already have my quote extended now

**Comment by GnubiBORED** [comment]
> 
> 
> > > Can't we circumvent this by making (say) 10 projects, thus 10 client secrets rotated to get more upload quota.
> > > Based my rough calculation, with 10K units, you can only upload 6 videos
> > 
> > 
> > you cant just open like 15 projects and use them for uploading, google detects those very fast, and terminates your google account!
> 
> yeah, was just an idea
> but I already have my quote extended now

how you get your quota extended? its your channel big enough?

**Comment by skeith** [comment]
> how you get your quota extended? its your channel big enough?

By filling this form 
`https://services.google.com/fb/forms/ytapiquotarequest/`

My channel is not big as it ony have less than 1000 subscribers but I do upload a lot. IIRC I have 2500+ videos on my channel. Back then before the 10K unit limit, I used to hit the 50 videos limit per day occasionally

**Comment by kootsoop** [comment]
This is a Google quota issue.
