### ISSUE TITLE
Is there a way to add line breaks to the description?

### ISSUE THREAD

**Issue by pfgp** [tokland/youtube-upload#272]
I am trying to add line breaks to my video descriptions.

youtube-upload ... --description="Line 1\r\nLine2" video.mp4

The above example doesn't work, but is it possible?

**Comment by mrbesen** [comment]
just ```\n``` works for me.

**Comment by televisedBow** [comment]
I'm using this in a Ruby environment and pass a string with `\n` in it. The description renders with line breaks for me.

**Comment by mrbesen** [comment]
when you have another program calling youtube_upload you might need to double escape the string with ```\\n``` and / or ```\"```

**Comment by ZainRizvi** [comment]
Seems like this issue can be safely closed

**Comment by jangxx** [comment]
I have a bash script where I'm trying to add newlines as well, but neither `desc="..\n.."` nor `desc="..\\n.."` worked for me when I put the variable in the description parameter (`--description="$desc"`). The literal \n was put in the description both times, so I would like to know how this is supposed to work as well.

**Comment by mrbesen** [comment]
but --description="..\n.." works for you?

**Comment by jangxx** [comment]
No it doesn't, neither with \n, nor with \\n. I just wanted to clarify that I use it in a script and with variables instead of manually typing in the shell. I'm not sure if there is any actual difference between the two, though.

**Comment by jangxx** [comment]
For future reference: The workaround I found to be working makes use of process substitution:

```bash
desc="something\n\with\nnewlines"
youtube-upload --description-file=<(echo -e "$desc") ...
```

It's not ideal but works reliably and without dirty hacks.

**Comment by kootsoop** [comment]
Closing as duplicate of #243
