### ISSUE TITLE
module 'oauth2client' has no attribute 'file'

### ISSUE THREAD

**Issue by tigofat** [tokland/youtube-upload#275]
Even when I add 'from oauth2client import file' to main.py it does not stop giving be this error.
AttributeError: module 'oauth2client' has no attribute 'file'

**Comment by csmccc** [comment]
from oauth2client import file

**Comment by rjbell4** [comment]
Or `pip install google-api-python-client==1.7.4` (or `pip3`)

**Comment by alopezag** [comment]
It works when adding the import into the file `youtube_upload/auth/__init__.py`

```python
from oauth2client import file
```

**Comment by ChillerDragon** [comment]
Shouldn't that be documented in the readme or fixed in the code?

**Comment by Juaran** [comment]
> Or `pip install google-api-python-client==1.7.4` (or `pip3`)

It works for me, tks!

**Comment by tthill** [comment]
> Or `pip install google-api-python-client==1.7.4` (or `pip3`)

This worked for me too.

**Comment by kootsoop** [comment]
Closing as duplicate of #245
