### ISSUE TITLE
Unable to capture video ID from output in a bash script

### ISSUE THREAD

**Issue by kevev** [tokland/youtube-upload#283]
I have a bash script that automates uploading. I am not able to capture any of the output into a variable, and I can't figure out why.

YT_VID_UP=$(/usr/local/bin/youtube-upload -t "$THIS_GAME_TITLE" --privacy=unlisted $WORK_DIR/$MP4_FILE)

In my bash script when I do echo $YT_VID_UP, the variable output is blank. But when I do the same commands directly at a bash prompt I get the video ID. I even tried capturing stdout & stderr, but they are blank. Any ideas what I may be doing wrong?

**Comment by kevev** [comment]
I ended up sending the output to a text file, and then reading it back into a variable. I don't know why redirecting output to variable didn't work. But my new solution is functional.

**Comment by HarringtonTom** [comment]
Hi man, would you be willing to share the bash script?

**Comment by kootsoop** [comment]
Did you need to say 

`export YT_VID_UP=$(/usr/local/bin/youtube-upload -t "$THIS_GAME_TITLE" --privacy=unlisted $WORK_DIR/$MP4_FILE)`

instead?
