### ISSUE TITLE
410 Unauthorized (youtubeSignupRequired)

### ISSUE THREAD

**Issue by Sandramann** [tokland/youtube-upload#288]
I got the following Issue, although youtube sign-in was performed and I've used the application numerous times before in exactly the same way.
The credentials are correct, and I've authed using the link and verification code method.

```
user@host:~/Downloads$ youtube-upload --title="asdasd" lol.mkv
Using client secrets: /home/user/.client_secrets.json
Using credentials file: /home/user/.youtube-upload-credentials.json
Start upload: lol.mkv
[RequestError] Server response: {
 "error": {
  "errors": [
   {
    "domain": "youtube.header",
    "reason": "youtubeSignupRequired",
    "message": "Unauthorized",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Unauthorized"
 }
}
```

After the third try or so it changes to:

```
[RequestError] Server response: {
 "error": {
  "errors": [
   {
    "domain": "youtube.quota",
    "reason": "quotaExceeded",
    "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e."
   }
  ],
  "code": 403,
  "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e."
 }
}
```

**Comment by wlerin** [comment]
In the browser they recently made the new (much worse) Upload form the default, although you can still get to the old one with a few extra clicks. I wonder if some backend changes also accompanied this, as the script stopped working around the same time.

**Comment by punqbund** [comment]
I'm getting the same error.

**Comment by reteps** [comment]
same error.

**Comment by oma0256** [comment]
@Sandramann @punqbund is this in `production` or `development`?

**Comment by matejmeglic** [comment]
I'm getting the same error, how did you guys solved this? @reteps @punqbund @Sandramann

**Comment by matejmeglic** [comment]
I figured it out. The problem was that my email was not connected to youtube channel (apparently one can do that) - after I authorized my youtube channel to receive information, everything worked.

**Comment by kootsoop** [comment]
@matejmeglic Thanks for letting us know what the fix was!

**Comment by tomislav-agilosit** [comment]
> I figured it out. The problem was that my email was not connected to youtube channel (apparently one can do that) - after I authorized my youtube channel to receive information, everything worked.

@matejmeglic Can you explain more about how to connect to youtube channel ie authorize yt channel to receive information?

**Comment by matejmeglic** [comment]
This is how I did it:

*use youtube-upload.sh to test uploading to youtube*

Follow https://github.com/tokland/youtube-upload

   - sudo pip install --upgrade google-api-python-client oauth2client
   progressbar2
   - wget https://github.com/tokland/youtube-upload/archive/master.zip
   - unzip master.zip
   - cd youtube-upload-master
   - sudo python setup.py install Set up OAuth file
   - log into google console (make sure you log in with account that has
   linked (is owner of) youtube channel - if you are having problems, that is
   the likely cause for them)
   - select project - new project - enter name of your project - click
   Create project
   - select newly created project
   - APIs & Services - click Enable APIs and Services - find all Youtube
   related APIs and enable them (I believe you only need Data API v3)
   - Click Create credentials
      - youtube api
      - other non-ui
      - public data
      - you get the key (restrict it if you want, I use it offline)
   - configure consent screen
      - external user type
      - submit information for verification
   - Create credentials
      - OAuth cliend ID
      - Application type: desktop app
      - name: youtube-upload - Create
   - download .json file (far right in OAuth 2.0 Client IDs)
   - modify path to .json file, title and path-to-test-video in
   youtube-upload.sh
   - terminal - chmod +x youtube-upload.sh (to make it executable)
   - terminal - ./youtube-upload.sh (run script test upload)
      - script will ask you to open link in a browser for validation
      - click on correct email profile --> then click on correct YOUTUBE
      ACCOUNT
      - Advanced
      - go to youtube uploading ...
      - Allow youtube to manage videos and account
      - Allow
      - Paste given code back to the terminal and press enter
      - if everything was done correctly, you should be able to upload
      videos - if you are getting 401, there is a problem with
Authorization with
      your youtube channel or smth, refer to tokland GitHub issues and
google for
      solving that part




Matej Meglič
***@***.***
+386 41 264 960

matejmeglic.com
