### ISSUE TITLE
i cant upload anymore

### ISSUE THREAD

**Issue by romainlavisse** [tokland/youtube-upload#291]
I am not working on youtube-upload anymore. However, if you prepare a PR, I'll gladly merge it. Please write me (@tokland) if you want to become the maintainer of youtube-upload.

**Describe the bug**
Today i try to upload but the thing is not working anymore

**Expected behavior**
Is it due to the deprecation of python 2 ??? because yesterday i wass working !

**Desktop (please complete the following information):**
 - OS: debian 8

**Comment by kootsoop** [comment]
I need more information rather than "not working anymore".  Are there error messages? Does it fail silently?
