### ISSUE TITLE
httplib2.RedirectMissingLocation: Redirected but the response is missing a Location: header.

### ISSUE THREAD

**Issue by xioayangguang** [tokland/youtube-upload#293]
Using client secrets: /root/.client_secrets.json
Using credentials file: /root/.youtube-upload-credentials.json
Start upload: 3.mp4
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 268, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 44, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 262, in main
    run_main(parser, options, args)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 180, in run_main
    video_id = upload_youtube_video(youtube, options, video_path, len(args), index)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/main.py", line 146, in upload_youtube_video
    chunksize=options.chunksize)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/upload_video.py", line 43, in upload
    RETRIABLE_EXCEPTIONS, max_retries=max_retries)
  File "/usr/local/lib/python2.7/dist-packages/youtube_upload/lib.py", line 76, in retriable_exceptions
    raise exc
httplib2.RedirectMissingLocation: Redirected but the response is missing a Location: header.

macos 10.14.1
python 2.7

**Comment by roycebank** [comment]
same

**Comment by tyc502044421** [comment]
same!

**Comment by TiborUdvari** [comment]
+1

**Comment by TiborUdvari** [comment]
Apparently there is a breaking change in `httplib2`. Here are the exact version of dependencies I am using.

```
pip3 install google-api-python-client==1.7.3 oauth2client==4.1.2 progressbar2==3.38.0 httplib2==0.15.0
```

Note that I am using `python3`.

**Comment by tyc502044421** [comment]
Ok thank you, check httplib2 version and reduce to 0.15.0 version

**Comment by feacluster** [comment]
I ran into same issue. Had to do the same thing posted above:

pip3 install google-api-python-client==1.7.3 oauth2client==4.1.2 progressbar2==3.38.0 httplib2==0.15.0

**Comment by xioayangguang** [comment]
我后来没有使用这个了，我用的php版本的上传可以参考 https://github.com/parth-grover/youtube_upload_script

**Comment by moodiest** [comment]
> Apparently there is a breaking change in `httplib2`. Here are the exact version of dependencies I am using.
> 
> ```
> pip3 install google-api-python-client==1.7.3 oauth2client==4.1.2 progressbar2==3.38.0 httplib2==0.15.0
> ```
> 
> Note that I am using `python3`.

Thank you, installed the same with pip2.7 instead of pip3 for my python 2.7 and all is working well. Much appreciated :)

**Comment by kootsoop** [comment]
Closing as seems to be a breaking change from `httplib2`.

**Comment by kootsoop** [comment]
OK, we really need to fix this!

**Comment by kootsoop** [comment]
Some info here: https://stackoverflow.com/questions/59815620/gcloud-upload-httplib2-redirectmissinglocation-redirected-but-the-response-is-m
