### ISSUE TITLE
Error running script: No module named apiclient.errors

### ISSUE THREAD

**Issue by matiasw** [tokland/youtube-upload#30]
Hi,
I have a problem with this script. When I run it with `youtube-upload`, I get
    Traceback (most recent call last): 
      File "/usr/local/bin/youtube-upload", line 23, in <module>
          import apiclient.errors
    ImportError: No module named apiclient.errors

**Comment by tokland** [comment]
`apiclient.errors` is part of `google-api-python-client` have you installed it?

**Comment by matiasw** [comment]
I had not; thanks for the advice. For anyone else with this issue, try `pip install --upgrade google-api-python-client`.
