### ISSUE TITLE
-RequestError- Server response: Not Found

### ISSUE THREAD

**Issue by feacluster** [tokland/youtube-upload#308]
I've been using the Youtube uploader without any issue for several months. All of a sudden today I started getting this error when uploading videos:

[RequestError] Server response: Not Found

**Comment by kachine** [comment]
The same problem has occurred in my environment (Ubuntu 18.04.5 LTS).
I've been using the Youtube uploader without any issue more than 22 months.

Just in case, I updated the resource of youtube-upload itself and its dependencies to the latest. But same problem continues.

**Comment by kachine** [comment]
This problem seems to be related to below:
https://github.com/googleapis/google-api-python-client/issues/1036#issue-704087354

The insert method of google-api-python-client, which is also used in youtube-upload seems not working correctly now.

**Comment by zilton7** [comment]
got the same error today too, any solutions?

**Comment by crow187** [comment]
Same issue here. Have a look in your "youtube-upload-credentials.json" file. In that file the "token_expiry" was set to yersterday (17.Sept.) I created a new credentials file but had no luck using it as its "token_expirey" was set to the creation date ("2020-09-18T06:31:14Z")

I have the suspicion that youtube has issues with their tokens? The new tokes should not be expired right away, shouldn't they?

**Comment by zilton7** [comment]
It seems to work using a direct approach (https://learndataanalysis.org/how-to-upload-a-video-to-youtube-using-youtube-data-api-in-python/), so I am pretty sure its an issue with youtube-upload.

**Comment by aleorda** [comment]
Youtube fixed the issue changing the rootUrl in https://www.googleapis.com/discovery/v1/apis/youtube/v3/rest from https://youtube.googleapis.com/ to https://www.googleapis.com/

**Comment by kachine** [comment]
I retried to upload using youtube-upload and it works fine again now.
This issue was probably Youtube server-side probrem like @aleorda mentions.

**Comment by feacluster** [comment]
Seems it is working back to normal now. I posted in stackoverflow and tagged youtube-api . I believe this is the preferred way to let youtube know about issues. Seems others had issues to: https://stackoverflow.com/questions/tagged/youtube-api
