### ISSUE TITLE
How can i bypass this or is impossible?

### ISSUE THREAD

**Issue by aldisonll** [tokland/youtube-upload#311]
```
youtube-upload` --title="Title" --auth-browser 6pWnchTqJyU
Using client secrets: /root/.client_secrets.json
Using credentials file: /root/.youtube-upload-credentials.json
Start upload: 6pWnchTqJyU
[RequestError] Server response: {
  "error": {
    "code": 403,
    "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.",
    "errors": [
      {
        "message": "The request cannot be completed because you have exceeded your \u003ca href=\"/youtube/v3/getting-started#quota\"\u003equota\u003c/a\u003e.",
        "domain": "youtube.quota",
        "reason": "quotaExceeded"
      }
    ]
  }
}

```

**Comment by feacluster** [comment]
I too have started getting this error after almost a year of it working without any issue . I have done some research and seems YouTube has changed their policy on "unverified 3rd party apps". Basically you have to get it verified for it to work now. I haven't started that yet. But some info here:

https://support.google.com/cloud/answer/7454865?hl=en&ref_topic=3473162
https://support.google.com/cloud/answer/6158849#userconsent

**Comment by keustii** [comment]
To bypass this, i looking for upload via selenium.  😉

**Comment by feacluster** [comment]
My understanding is selenium solution is against their Terms of Service. So you risk getting your account suspended ( worse case scenario ). It is impossible to deal with a human at YouTube so I would rather not roll the dice with their flagging algorithms....
