### ISSUE TITLE
How to get a credentials file and switch to another youtube channels?

### ISSUE THREAD

**Issue by stephane-archer** [tokland/youtube-upload#319]
Hi,

I have multiple youtube chanels.
I used `--client-secrets` to connect to the first channel I wanted to upload to.
**Now I want to upload to another channel.**
If I use `--client-secrets`, will it still ask me witch youtube channel I want to upload to?
Or shoud I use the option `--credentials-file`?
If so, how do I get a credentials-file for each of my youtube channels?

Thank you

**Comment by pvalena** [comment]
You can remove the default credentials file `~/.youtube-upload-credentials.json`, and it will ask again.
