### ISSUE TITLE
__init__.py   THROWS 2 ERRORS FOR ME

### ISSUE THREAD

**Issue by helloimdomas** [tokland/youtube-upload#323]
### COULD NOT RESOLVE THEM

Tuple expression not allowed in type annotation
  Use Tuple[T1, ..., Tn] to indicate a tuple type or Union[T1, T2] to indicate a union type

Here is screenshot
![image](https://user-images.githubusercontent.com/76450741/112993021-6bbfdc80-9171-11eb-8ad1-39c9403a2c37.png)

**Second error:**

ImportError: cannot import name 'By' from 'selenium_firefox.firefox' (C:\Users\d\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium_firefox\firefox.py)

Here are screenshots
![image](https://user-images.githubusercontent.com/76450741/112993324-c35e4800-9171-11eb-832f-a2abee912682.png)

![image](https://user-images.githubusercontent.com/76450741/112993162-8f832280-9171-11eb-9eb4-a29b90212b2a.png)

**Comment by ssyzyg** [comment]
@domasb2005 May I know how did you fix "ImportError" issue?
