### ISSUE TITLE
Videos automatically being locked for "spam, deceptive practices and scams policy" after processing is done

### ISSUE THREAD

**Issue by apathy** [tokland/youtube-upload#325]
~~Hey, any video I try upload using youtube-upload no matter if it's 3-5 seconds or 10 minutes+ will automatically get locked for the same reason. Anyone know why this is happening and a way to prevent it?~~

Got this working now.

**Comment by grandmaestr** [comment]
Can you share how you managed to get this issue fixed? I'm having the same problem.

**Comment by apathy** [comment]
> Can you share how you managed to get this issue fixed? I'm having the same problem.

The fix went nowhere as a day later it returned again so I switched to https://github.com/linouk23/youtube_uploader_selenium and made it headless, had no issue since then.

**Comment by gerry-momo** [comment]
you need publish your application  , but google not allow this api using by personal. (After 2020-07
