### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by Mte90** [tokland/youtube-upload#33]
I think that for the upload is useful a progress bar about the upload.

**Comment by tokland** [comment]
If module `python-progressbar` is installed, you see a progres bar.

**Comment by Mte90** [comment]
Uh okay, in the readme is not specified that `python-progressbar` is mandatory for the script because start without message about this.

**Comment by tokland** [comment]
Indeed, I just add this info to the readme. Thanks for reporting.
