### ISSUE TITLE
No such option "unlisted" / "private"

### ISSUE THREAD

**Issue by binyominzeev** [tokland/youtube-upload#35]
How can I upload videos with private or unlisted settings?

I could not find in help and in code. In previous version there was an option "--unlisted" or "--private" but now it just no longer works for me.

**Comment by tokland** [comment]
$ youtube-upload -h |& grep public
  --privacy=STRING      Privacy status (public | unlisted | private)

**Comment by AzapiSolutions** [comment]
I too
