### ISSUE TITLE
"Add to Playlist" functionality

### ISSUE THREAD

**Issue by bazzinotti** [tokland/youtube-upload#36]
youtube-upload --help did not show any option to add the new video to a playlist after upload. I am aware the V2 API version of this software had this feature, and that this version upgraded to API V3. Is this feature yet in the software, or planned to be implemented? If not, I may try.

**Comment by tokland** [comment]
Correct, it's not implemented here and not planned to be. But pull requests welcome!

**Comment by sbma44** [comment]
@bazzinotti eyes on this PR welcome: https://github.com/tokland/youtube-upload/pull/46
