### ISSUE TITLE
Upload result "Raw file: Unknown"

### ISSUE THREAD

**Issue by SnoOpyMinhThang** [tokland/youtube-upload#38]
In previous version of youtube-upload + API v2 (deprecated), Raw file option alway same with upload file.
But with this version: 0.8 + API v3, "Raw file" of every videos alway are "Unknown".
This property play important role in video SEO ranking.
![screenclip](https://cloud.githubusercontent.com/assets/10328775/8104701/e42d0cfc-105c-11e5-96cc-94d007ebac36.png)

Any workaround, please!

**Comment by tokland** [comment]
Known bug in gdata, nothing I can do, sorry!

https://code.google.com/p/gdata-issues/issues/detail?id=7140
