### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by PureDude** [tokland/youtube-upload#39]
Hello, I have got this error when upload is triggered by cronjob (user: root):
File "/usr/bin/youtube-upload", line 191, in <module>
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/lib/python2.6/site-packages/youtube_upload/lib.py", line 35, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/bin/youtube-upload", line 188, in main
    run_main(parser, options, args)
  File "/usr/bin/youtube-upload", line 147, in run_main
    video_id = upload_video(youtube, options, video_path, len(args), index)
  File "/usr/bin/youtube-upload", line 90, in upload_video
    title = u(options.title)
  File "/usr/lib/python2.6/site-packages/youtube_upload/lib.py", line 21, in to_utf8
    return s.decode(current).encode("UTF-8") if s and current != "UTF-8" else s
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)

Title, description and tags contain special characters such as "äöüß"... Strangely, when I start the upload-shell-script directly from the console (user: root) there are no problems!!

The following adjustments work for me in both cases with special characters (cronjob, console):
"""Upload video with index (for split videos)."""
    u = lib.to_utf8
    #title = u(options.title)
    title = (options.title)
    #description = u(options.description or "").decode("string-escape")
    description = (options.description or "").decode("string-escape")
    #tags = [u(s.strip()) for s in (options.tags or "").split(",")] 
    tags = [s.strip() for s in (options.tags or "").split(",")]
    #ns = dict(title=u(options.title), n=index+1, total=total_videos
    ns = dict(title=(options.title), n=index+1, total=total_videos)
    complete_title = \

(Environment: CentOS 6.2, Pyhton 2.6.6)

Thx, Stephan

**Comment by tokland** [comment]
The problems is that this conversion needs to be done for non UTF-8 shells (particularly, for Windows). I tried with my cron, it worked. Maybe the encoding used in your cron is different? try to set it: http://askubuntu.com/a/9830/193388

**Comment by PureDude** [comment]
Thanks for your help. I will try it as soon as possible...

**Comment by PureDude** [comment]
Following lines at the beginning in crontab file has solved the problem:
LANG=de_DE.UTF-8
LANGUAGE=de
LC_CTYPE=de_DE.UTF-8
PYTHONIOENCODING=utf8
http://askubuntu.com/questions/9743/cron-is-changing-encoding/9830#answer-606602

Thanks for your feedback!
Btw... nice project!
