### ISSUE TITLE
Is there a way to use proxy only for youtube-upload?

### ISSUE THREAD

**Issue by whitesiroi** [tokland/youtube-upload#40]
Hi,

Is there a way to use proxy only for youtube-upload and not for other services?
I set proxies with export:
$ export http_proxy=http://user:password@host:port
$ export https_proxy=$http_proxy
And, they does work great, but it's globally, so when I curl or download/upload other stuff to other sites it's very slow. So, maybe, there is a way to use proxy only for youtube-upload? And, I'll be able to use other services without proxy.

Thank you & regards,
Artem

**Comment by tokland** [comment]
To be honest, I had no tried this with the new API. Now I tried to set those variables and no proxy was used. Are you sure the proxy is being used for you?

**Comment by whitesiroi** [comment]
Thank you for your reply.

>> Are you sure the proxy is being used for you?
Yes, the whole month I used it without a proxy - it was super fast )
Now, I have some problems with youtube :) so I added proxies through export and it does work, but my uploading speed is vary from 1~3Mbit with proxy, and 18~25Mbit without proxy.

**Comment by tokland** [comment]
Ok, I'll try something more. Answering your question, try:

``` 
$ http_proxy=xyz http_pryxs=xyz youtube-upload ...
```

**Comment by whitesiroi** [comment]
You're the man )

It does work with >> http_proxy=xyz https_proxy=xyz youtube-upload ...

Thank you very much for your help & this awesome tool.

**Comment by tokland** [comment]
:)
