### ISSUE TITLE
Failed (unable to convert video file)

### ISSUE THREAD

**Issue by kangoo13** [tokland/youtube-upload#41]
Hello,

I have this error since this morning. I am trying to upload a .mp4 file (I already uploaded a lot of files like that) and the error does not come from the file itself because I can upload it manually..
When I launch the script there are no errors, it gives me the youtube link but the video is unavailable because of "Failed (unable to convert video file)"

Can you help me ?

Thanks !

**Comment by tokland** [comment]
No idea, did you google the error?

**Comment by kangoo13** [comment]
Yes it's a kind of random issue, i'll manage to find out because I need to, thanks for the help !
