### ISSUE TITLE
-bash: --description= : command not found

### ISSUE THREAD

**Issue by nadirg** [tokland/youtube-upload#42]
Hello

I installed everything, ran a test and managed to upload a video with the simple method (just the tile)

Now, when I try to upload with all meta, I'm getting an error.

I don't know what went wrong.

My query

youtube-upload --title="How To Do: Dumbbell Twist - Russian Standing | Ab Workout Exercise Video | Fitway" 
               --description="Stand straight with feet should with apart. Hold the dumbbell out in front at waist" \
               --category=#Lifestyle \
               --tags="fitness,workout,exercises,gym,app,android,iPhone" \
               --client-secrets=my_client_secrets.json \
               --credentials-file=my_credentials.json \
               dag_01_05.mp4

Error message:

-bash: --description=Stand straight with feet should with apart. Hold the dumbbell out in front at waist: command not found

Anyone has an idea?

Thanks

**Comment by tokland** [comment]
You're missing a ```\```at the end of the first line.

**Comment by nadirg** [comment]
Ah
