### ISSUE TITLE
No module named apiclient.errors

### ISSUE THREAD

**Issue by ludovicsclain** [tokland/youtube-upload#45]
Hi,
I'm a complete newbie and I try to follow your step to upload video on my YouTube Channel and I've got this error : 
 File "/usr/local/bin/youtube-upload", line 23, in <module>
    import apiclient.errors
ImportError: No module named apiclient.errors
Any idea on how to resolve this ? I made something wrong ?
Regards,
Ludovic

**Comment by tokland** [comment]
Did you install the dependencies specified in the README? 

```pip install --upgrade google-api-python-client progressbar```

**Comment by ludovicsclain** [comment]
I've just do it, here results :

pip install --upgrade google-api-python-client progressbar
You are using pip version 6.0.8, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting google-api-python-client
  Downloading google-api-python-client-1.4.1.tar.gz (41kB)
    100% |################################| 45kB 2.3MB/s                        
Collecting progressbar
  Downloading progressbar-2.3.tar.gz
Collecting httplib2>=0.8 (from google-api-python-client)
  Downloading httplib2-0.9.1.tar.gz (205kB)
    100% |################################| 208kB 1.3MB/s                       
Collecting oauth2client>=1.4.6 (from google-api-python-client)
  Downloading oauth2client-1.4.12.tar.gz (49kB)
    100% |################################| 53kB 2.3MB/s                        
Collecting six>=1.6.1 from https://pypi.python.org/packages/3.3/s/six/six-1.9.0-py2.py3-none-any.whl#md5=9ac7e129a80f72d6fc1f0216f6e9627b (from google-api-python-client)
  Downloading six-1.9.0-py2.py3-none-any.whl
Collecting uritemplate>=0.6 (from google-api-python-client)
  Downloading uritemplate-0.6.tar.gz
Collecting pyasn1>=0.1.7 (from oauth2client>=1.4.6->google-api-python-client)
  Downloading pyasn1-0.1.8.tar.gz (75kB)
    100% |################################| 77kB 5.2MB/s                        
Collecting pyasn1-modules>=0.0.5 (from oauth2client>=1.4.6->google-api-python-client)
  Downloading pyasn1-modules-0.0.6.tar.gz
Collecting rsa>=3.1.4 (from oauth2client>=1.4.6->google-api-python-client)
  Downloading rsa-3.1.4.tar.gz
Collecting simplejson>=2.5.0 from https://pypi.python.org/packages/source/s/simplejson/simplejson-3.7.3.tar.gz#md5=117346e5ee4ed4434ffe485f8e58f5ed (from uritemplate>=0.6->google-api-python-client)
  Downloading simplejson-3.7.3.tar.gz (74kB)
    100% |################################| 77kB 4.5MB/s                        
Installing collected packages: simplejson, rsa, pyasn1-modules, pyasn1, uritemplate, six, oauth2client, httplib2, progressbar, google-api-python-client
  Found existing installation: simplejson 3.6.5
    Uninstalling simplejson-3.6.5:
      Exception:
      Traceback (most recent call last):
        File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 232, in main
          status = self.run(options, args)
        File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 347, in run
          root=options.root_path,
        File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 543, in install
          requirement.uninstall(auto_confirm=True)
        File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 667, in uninstall
          paths_to_remove.remove(auto_confirm)
        File "/usr/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 126, in remove
          renames(path, new_path)
        File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 316, in renames
          shutil.move(old, new)
        File "/usr/lib64/python2.7/shutil.py", line 300, in move
          rmtree(src)
        File "/usr/lib64/python2.7/shutil.py", line 252, in rmtree
          onerror(os.remove, fullname, sys.exc_info())
        File "/usr/lib64/python2.7/shutil.py", line 250, in rmtree
          os.remove(fullname)
      OSError: [Errno 13] Permission denied: '/usr/lib64/python2.7/dist-packages/simplejson/decoder.py'

**Comment by tokland** [comment]
http://stackoverflow.com/questions/25816674/pip-is-not-able-to-install-packages-correctly-permission-denied-error
