### ISSUE TITLE
ImportError: No module named playlists

### ISSUE THREAD

**Issue by 7ota** [tokland/youtube-upload#47]
Hello dir ,

Thanks for your work last branch show error : 
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 30, in <module>
    import playlists
ImportError: No module named playlists

**Comment by tokland** [comment]
Ups, I just tested it locally. I'll check with the commiter. For now: 61cccc5. Thx!

**Comment by tokland** [comment]
And 0228617, let's see how this works.
