### ISSUE TITLE
problem with uploading by browsers 

### ISSUE THREAD

**Issue by badershs** [tokland/youtube-upload#48]
Hi i tried to upload by commend line and every thing is good but the problem now is when i tried to use the same commend from browser the code is not working they asked me to Enter verification code 
and i didnt get the link for verification  
i'm working on php

**Comment by tokland** [comment]
I don't understand. If you passed the --auth-browser option, no verification code should be asked. Can you send a screenshot?

**Comment by badershs** [comment]
no i didnt pass any --auth-browser to the commend 
when i pass  --auth-browser i dont get any thing the page will be empty

**Comment by badershs** [comment]
but when i pass it to my commend line inside my server everything is working good

**Comment by tokland** [comment]
I gather you are running it from a web frontend. The link for the veritication is output to the stderr, your PHP script should capture from that channel and pass along the link to the user. But I am afraid this is not a bug, just a usage problem from PHP. You may get more help from a PHP forum (I don't know the language).
