### ISSUE TITLE
give title for all my file which are uploading to youtube

### ISSUE THREAD

**Issue by badershs** [tokland/youtube-upload#49]
Hi is it possible to give title for each file ? 
for example the commend line code is 
 youtube-upload    --title="A.S. Mutte"  a.mp4   b.mp4 c.mp4 d.mp4 
with this commend i upload 4 file to youtube but all of them has the same name A.S. Mutte
what is the commend line that i can define name for each of this files

**Comment by tokland** [comment]
You'll have to execute the script for each video. Multiple files are used to upload a splitted video, not different ones.
