### ISSUE TITLE
socket.error: [Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by Marc4it** [tokland/youtube-upload#50]
I'm currently facing this problem, this will happen in some video when batch uploading. Anything i can do?
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 5, in <module>
    main.run()
  File "/Library/Python/2.7/site-packages/youtube_upload/main.py", line 214, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/Library/Python/2.7/site-packages/youtube_upload/lib.py", line 35, in catch_exceptions
    fun(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/youtube_upload/main.py", line 211, in main
    run_main(parser, options, args)
  File "/Library/Python/2.7/site-packages/youtube_upload/main.py", line 153, in run_main
    video_id = upload_youtube_video(youtube, options, video_path, len(args), index)
  File "/Library/Python/2.7/site-packages/youtube_upload/main.py", line 121, in upload_youtube_video
    request_body, progress_callback=progress.callback)
  File "/Library/Python/2.7/site-packages/youtube_upload/upload_video.py", line 37, in upload
    RETRIABLE_EXCEPTIONS, max_retries=max_retries)
  File "/Library/Python/2.7/site-packages/youtube_upload/lib.py", line 71, in retriable_exceptions
    raise exc
socket.error: [Errno 54] Connection reset by peer

**Comment by tokland** [comment]
This happens a lot? I've never got this error. The problem is that socket errors usually are not retriable, so raising an exception is the safest we can do.

**Comment by Marc4it** [comment]
It happen 3 to 4 times in 20 videos. Thanks for your suggestion, but i'm not that good in scripting. Can you teach me some example for this? That will be really appreciate! I'm actually doing these all in .sh, example below.

youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4
youtube-upload --title="" --client-secrets=/users/punya/youtube-upload-master/client_secrets.json --description="" --tags="" --thumbnail="" --playlist="" --privacy="unlisted" /users/x.mp4

I just repeating these all command over and over again, i'm thinking to let it loop again when a error appeared but i don't know how to wrap it as you said.

**Comment by tokland** [comment]
Learn some bash, it will payoff: http://www.howtogeek.com/67469/the-beginners-guide-to-shell-scripting-the-basics/

For example, this uploads all videos in directory "videos", with retrying:
```
for FILE in videos/; do
  while ! youtube-upload [...] $FILE; do
    echo "failed, retrying"
  done
done

**Comment by Marc4it** [comment]
Thanks Arnau, will try it!
