### ISSUE TITLE
How to change the channel I upload to ? 

### ISSUE THREAD

**Issue by Ternoc** [tokland/youtube-upload#52]
I would like to change the channel I upload to and change the auth information. 

Thank you

**Comment by tokland** [comment]
Check the README, pull requests welcome.

**Comment by Ternoc** [comment]
I have 2 different youtube channel. I just want to change the auth informations

**Comment by Skylion007** [comment]
This feature already exists, You just have to change the credential file by specifying which file you want to save your auth information to with the --credential parameter.

**Comment by tokland** [comment]
Indeed, option ```--credentials-file``, it will work for the channel you selected on its creation.
