### ISSUE TITLE
Failed Upload Cancellation

### ISSUE THREAD

**Issue by dozyh** [tokland/youtube-upload#54]
Hello,

It seems that even if an upload fails mid-file YouTube will happily process and publish that which it has received. At this time is there any way I can check for this situation in my scripts which use youtube-upload and ask YouTube to cancel the corresponding processing/publishing? I don't think I get a video ID back as a result if the upload fails.

**Comment by tokland** [comment]
Ugly. Maybe you can file in the API project? https://github.com/google/google-api-python-client
