### ISSUE TITLE
Videos longer than 15' 

### ISSUE THREAD

**Issue by pau-amaro-seoane** [tokland/youtube-upload#58]
Hi:

thanks for the script. I have noticed that I can upload videos longer than 15 minutes via the web interface, but the script leads to youtube displaying the error message that " This video has been removed because it is too long. "

The log did not show anything strange:

youtube-upload --title='LLL' Freitag_1.avi                                       
Using client secrets: /home/XXX/.client_secrets.json
Using credentials file: /home/XXX/.youtube-upload-credentials.json
Start upload: Freitag_1.avi
100% |####################################################################################################################| Time: 0:00:39  10.05 MB/s
Video URL: https://www.youtube.com/watch?v=R6X6ssrCZPk
R6X6ssrCZPk

I am using the same account, of course, I have enabled the long-movies option and I have managed to upload a 45 minutes one without an issue using the web interface.

Thanks,

Pau

**Comment by tokland** [comment]
Looks like https://code.google.com/p/gdata-issues/issues/detail?id=7213

**Comment by pau-amaro-seoane** [comment]
Arnau? Catala?

In any case, I am not sure what's the fix... I did not understand what's a " the API v3 in premium accounts". My account is in any case "normal", meaning that I have not paid anything or upgraded anything.

I have to upload some 90 science videos, all of them longer than 15 minutes. If you can help me with this, I would be very grateful.

thanks

**Comment by tokland** [comment]
Català :)

Ok, I'll look into it, and last try to reproduce the problem (I'll enable the feature: https://support.google.com/youtube/answer/72851?hl=en&rd=1)

One problem, though: if it's a bug in the Youtube API, there is nothing we can do other than reporting it. And judging by the attention that similar report got, it does not look too well...

**Comment by pau-amaro-seoane** [comment]
aixó em vindria de meravella... altrament no sé què faré

**Comment by Sunka** [comment]
Same proble here.
Video uploaded but the error message that " This video has been removed because it is too long. "
It is 25 minutes long video.
I have enabled in youtube settings for upload videos longer than 15 minutes.
Any help?
