### ISSUE TITLE
Credentials vs Secrets

### ISSUE THREAD

**Issue by funkenstrahlen** [tokland/youtube-upload#61]
Hey,

I just try to setup the uploader. In your example you provide `--client-secrets` and `--credentials-file`. I can not see the difference.

After setting up API access to my Youtube account I could download the OAuth2 secrets file. It has the similar json structure as the example secrets file in this repository.

Where can I get the credentials file? The Readme docu as a little confusing on this topic as *credentials* and *secrets* are used inconsistently.

Can you help?

**Comment by meredrica** [comment]
you have to start the script with the gui option once iirc

**Comment by funkenstrahlen** [comment]
I use it on a vserver. No gui possible.

**Comment by meredrica** [comment]
then just do it locally to get the files and copy them over. that's what i did.

**Comment by tokland** [comment]
client-secrets: The package provides one, it's the app identification. 
credentials: this file is created on the first upload and stored for later uses. 

gui: no need for gui. On the first upload you'll be asked to check a URL and insert the validation code you'll get there.

**Comment by funkenstrahlen** [comment]
Thank you, got it working now.
