### ISSUE TITLE
Authentication problem: [FlowExchangeError] invalid_grantCode was already redeemed.

### ISSUE THREAD

**Issue by gdetrez** [tokland/youtube-upload#62]
I'm trying to upload videos to youtube. Everithing goes well at first: I get a url from `youtube-upload`, log in my google account and get a token but when I enter the token in the terminal I get this error:
```
[FlowExchangeError] invalid_grantCode was already redeemed.
```

**Comment by tokland** [comment]
Cannot reproduce. It seems like the code is expired/used, which makes no sense. Did it happen again?

**Comment by tokland** [comment]
No feedback
