### ISSUE TITLE
Ability to log output

### ISSUE THREAD

**Issue by sabian2008** [tokland/youtube-upload#63]
Hello

First of all, thanks for this great script. It's a time-saver.

I was wondering how might I be able to write output to a file, in order to run in background through ssh and keep track of progress. I've tried normal output redirection in bash (>) but it doesn't work. I've read that my aproach would only redirect output of main.py itself and not modules. It also seems it can be solved redefining sys.stout but can't seem to find how.

Excuse me if I'm talking nonsense. I know nothing about python.

Thanks in advance,

**Comment by tokland** [comment]
To redirect both stderr and stdout, try: `&>` instead of `>`
