### ISSUE TITLE
Uploaded videos are not monetized by default, even if the youtube default settings suggest this

### ISSUE THREAD

**Issue by RonnyS123** [tokland/youtube-upload#64]
Won't work!

**Comment by Phoenix616** [comment]
This is probably caused by the inability to upload a video without any information, e.g. it needs at least a title. And I guess if one is there youtube won't apply the default settings anymore so my guess is that it won't be possible to fix that on the youtube-upload end.

**Comment by tokland** [comment]
No idea, sorry. If you manage to find in the APIv3 some reference to it, I'll apply the changes.
