### ISSUE TITLE
Upload by email

### ISSUE THREAD

**Issue by cikatomo** [tokland/youtube-upload#65]
Hi,
why did you remove upload by email and password if that method still works?

**Comment by tokland** [comment]
It works with the API v3? Can you point to the documentation?

**Comment by cikatomo** [comment]
No, I can't. I didn't know there's no more client login in v3. Are you saying that we have to use browser now? Can we make some script that acts as a browser and get a token?

**Comment by Skylion007** [comment]
This is already implemented just use the flag --auth-browser.

**Comment by tokland** [comment]
Yes, AFAIK in v3 the token is the only available auth scheme. As Skylion007 says, you have a GUI to do it, but in any case you need manual processing (only the first time). Of course, it could be automated to put the email, password, confirm and get the validation code, but that's out of the scope of the script.
