### ISSUE TITLE
AttributeError: 'module' object has no attribute 'client'

### ISSUE THREAD

**Issue by logological** [tokland/youtube-upload#7]
Apologies if I'm committing a very elementary mistake (I have no experience with Python) but when I install and run the script according to the instructions in the README file, it fails as follows:

$ youtube-upload --title=foo --description=bar --category=Music --client-secrets=mysecrets.json baz.mkv
Using client secrets: mysecrets.json
Using credentials file: /home/psy/.youtube-upload-credentials.json
Traceback (most recent call last):
  File "/usr/bin/youtube-upload", line 164, in <module>
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/lib/python2.7/site-packages/youtube_upload/lib.py", line 21, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/bin/youtube-upload", line 161, in main
    run_main(parser, options, args)
  File "/usr/bin/youtube-upload", line 121, in run_main
    youtube = youtube_upload.auth.get_resource(client_secrets, credentials)
  File "/usr/lib/python2.7/site-packages/youtube_upload/auth.py", line 36, in get_resource
    get_flow = oauth2client.client.flow_from_clientsecrets
AttributeError: 'module' object has no attribute 'client'

Am I perhaps missing a dependency that's not listed in the instructions?

**Comment by tokland** [comment]
import apiclient.discovery is responsible for importing oauth2client.client. Mmm, distro? is google-api-python-client installed?

**Comment by tokland** [comment]
No feedback. Closing. This should work, anyway:

```
$ sudo pip install --upgrade google-api-python-client
```
