### ISSUE TITLE
How to Uninstall?

### ISSUE THREAD

**Issue by adeluccar** [tokland/youtube-upload#72]
I did a ```pip uninstall youtube-upload``` but it failed to uninstall the utility.
How should I go about this?

**Comment by tokland** [comment]
AFAIK Pypi has a very old youtube-upload package, not this one. Which error? You can try to delete the files manually, in any case.

**Comment by adeluccar** [comment]
Where are the files?

**Comment by tokland** [comment]
It depends on your distro. Run "locate youtube-upload" to seek for the dirs.
