### ISSUE TITLE
Play list not found

### ISSUE THREAD

**Issue by Pavel-II** [tokland/youtube-upload#73]
Play list not found.
I`m copy play list name from youtube to upload param, but it`s not found:
youtube-upload-master/bin/../youtube_upload/playlists.py:10: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if item.get("snippet", {}).get("title") == title:
The name of the playlist in Cyrillic.

**Comment by tokland** [comment]
06fe308 should fix it, please give feedback if you can test it. Thanks for reporting.
