### ISSUE TITLE
Cannot add video to playlist (error: nsufficientPermissions)

### ISSUE THREAD

**Issue by alanjohnmiller** [tokland/youtube-upload#74]
When I attempt to upload a video with --playlist option, I get the following error after the video is uploaded. The playlist "2013" exists, and is public. When I omit the --playlist option, no error is thrown.

e.g.
youtube-upload \
   --client-secrets="/root/upload-clips.client_secrets.json" \
   --credentials-file="/root/upload-clips.credentials.json" \
   --location="latitude=-29.3,longitude=157.6" \
   --privacy="private" \
   --tags="test,tags" \
   --description="Test Description" \
   --title="Test Video" \
   --category="Education" \
   --playlist="2013" \
   "/data/master/video/Test.mov"

Using client secrets: /root/upload-clips.client_secrets.json
Using credentials file: /root/upload-clips.credentials.json
Using category: Education (id=27)
Start upload: /data/master/video/Test.mov
100% |###############################################################################################################################| Time: 0:00:03   4.04 MB/s
Video URL: https://www.youtube.com/watch?v=IP3iRpBQgEs
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 10, in <module>
    main.run()
  File "/usr/local/lib/python2.7/site-packages/youtube_upload/main.py", line 236, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "/usr/local/lib/python2.7/site-packages/youtube_upload/lib.py", line 44, in catch_exceptions
    fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/youtube_upload/main.py", line 233, in main
    run_main(parser, options, args)
  File "/usr/local/lib/python2.7/site-packages/youtube_upload/main.py", line 184, in run_main
    title=options.playlist, privacy=options.privacy)
  File "/usr/local/lib/python2.7/site-packages/youtube_upload/playlists.py", line 42, in add_video_to_playlist
    playlist_id = get_playlist(youtube, title) or \
  File "/usr/local/lib/python2.7/site-packages/youtube_upload/playlists.py", line 8, in get_playlist
    results = request.execute()
  File "/usr/local/lib/python2.7/site-packages/oauth2client/util.py", line 140, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/http.py", line 729, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/youtube/v3/playlists?alt=json&part=id%2Csnippet&mine=true returned "Insufficient Permission">

The video itself does upload, but the playlist is not set. 
When I access "https://www.googleapis.com/youtube/v3/playlists?alt=json&part=id%2Csnippet&mine=true" I get the following error:

{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}

I am signed up using OAuth 2.0 client IDs.

Does anyone have any idea why this is happening? The video uploads, but the playlist is not set. If I do not use the --playlist option, then the video uploads without any error.

Cheers
AJ

**Comment by tokland** [comment]
That 403 is normal if you access this URL from a browser. I cannot reproduce the problem, I uploaded a video to a playlist. First it didn't exist, it created it. The second one it just added it to the now existing playlist.

I made a change so the response of the server is printed so we know what the problem is. Try: 75472b9

**Comment by alanjohnmiller** [comment]
I have fixed this problem using the following procedure. Most of the procedure is the normal setup routine for youtube-upload. I have only tested this procedure on Centos 6.6, but I assume it will be the same on most Linux types.

Some background. When youtube-upload is first installed and used, it creates:
a. A client_secrets file in /usr/local/share/youtube_upload/client_secrets.json. 
b. During authorization it also creates a credentials file in ~.youtube-upload-credentials.json

If you have multiple youtube accounts connected to a single google email address (some of which have not yet had channels created), you will find that Firefox has authorization errors. I had to use MS Internet Explorer and logon to the google email address, and then carefully select the youtube linked account to that address before proceeding with authorization otherwise authorization did not validate as expected. Make sure each Google email address has had Youtube API enabled in Google Developers Console.

On the upload box (assuming linux)
Note 1: Assumes youtube-upload is already installed as per Arnau's instructions.
Note 2: Since I am using /root, I stored my files in /root. I assume that if you are using a different account, you would store in /home/user but I have not tested this.

1. Remove all client_secrets files for youtube stored in users home on upload machine. I removed all in /root.

2. Remove all credential files for youtube stored in users home on upload machine. I removed all in /root.

3. Remove ~.youtube-upload-credentials.json on upload machine if it exists. I removed from /root.

4. Now perform an upload of a test video.

5. e.g. youtube-upload \
  --privacy="private" \
  --location="latitude=-28.37,longitude=121.67" \
  --title="Test Video" \
  --description="Test Description" \
  --category="Education" \
  --tags="test,tags" \
  --playlist="Test" \
  "/data/master/video/test.mp4"

5. You will be prompted to enter some text into a browser (remember if you have multiple channels linked to one email address, you will need to use MS Internet Explorer due to errors in Firefox under those conditions). Enter http text into a browser, making sure you select the correct youtube account linked to that address if multiple accounts are presented, and you will be given an authorization code from Google which you will need to enter next to the "Enter verification code:" prompt. Copy the verification code and enter it for youtube-upload.

7. This creates new files in the following locations.
    a. A client_secrets file in /usr/local/share/youtube_upload/client_secrets.json. 
    b. During authorization it also creates a credentials file in ~.youtube-upload-credentials.json

    The above process is the normal youtube-upload process for setup. If you are only using youtube-upload for a single Google email with one youtube account, then that is the normal procedure done.

    The following applies to using youtube-upload with multiple Google email accounts.

8. Copy/Move created credentials and client_secrets to new files.
cp /usr/local/share/youtube_upload/client_secrets.json /root/upload-new-channel.client_secrets.json
mv /root/.youtube-upload-credentials.json /root/upload-new-channel.credentials.json

9. In future uploads for that channel, use the following options:
  --client-secrets="/root/upload-new-channel.client_secrets.json" \
  --credentials-file="/root/upload-new-channel.credentials.json" \

10. To use a different channel, on your browser log off from the 1st Google email address, log onto another Google email address with a different youtube account, and process steps 3 to 9 for the different channel, remembering to use different file names for the client_secrets and credentials json files.

Once I did this process, and found the error with Firefox validation on email accounts that have multiple youtube accounts on a single Google email address, everything worked, and the playlist error was fixed. 

Issue: The main issue seemed to be that Firefox was not allowing me to create an authorization code for the correct youtube account when I had multiple youtube accounts linked to a single email address. Then, youtube-upload would create a credentials file that would allow me to upload the video (since that appears to be linked to the email address), but would not allow me to select a playlist due to permissions errors on Youtube, because the playlist seems to be linked only to the specific youtube account.

I hope that helps anyone who has:
a. Multiple youtube accounts linked to a single email address, or;
b. Those who want to upload to multiple channels on the same upload machine.

**Comment by tokland** [comment]
Wow, thanks for the detailed explanation! I'm sure it will help others with the same problem.
