### ISSUE TITLE
What do I put in the credentials file

### ISSUE THREAD

**Issue by Sjansbuzze** [tokland/youtube-upload#75]
I know the client-secrets.json file.
But what is the Credentials file ?
Does someone have an example ?

**Comment by tokland** [comment]
The credentials file is created when you authenticate (location $HOME/.youtube-upload-credentials.json)

**Comment by Sjansbuzze** [comment]
Hi tokland,
What do you mean "when I authenticate.." ? Where do I have to authenticate ?

When I requested my Client ID & client secret in the youtube API, I was able to create my client-secrets.json. Something like this:
    "installed": {
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "client_secret": "S0m5thingzersfsqdf",
        "token_uri": "https://accounts.google.com/o/oauth2/token",
        "client_email": "",
        "redirect_uris": ["urn:ietf:wg:oauth:2.0:oob", "oob"],
        "client_x509_cert_url": "",
        "client_id": "123456789somenumbers.apps.googleusercontent.com",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs"
    }
}

**Comment by tokland** [comment]
Try to upload a video and you'll be asked to authenticate (you'll get a URL).

**Comment by Sjansbuzze** [comment]
It asked indeed for an authentication code. I didn't know what to fill in.
I'll try it again this evening when I'm back home.

**Comment by mykeylynx** [comment]
Can we upload multiple videos? What is the command?


    _____________________________

**Comment by Sjansbuzze** [comment]
Tokland, I succeeded in uploading my video. Thanks !
mykeylynx, I never tried with more than one. Sorry

**Comment by JacekZST** [comment]
You receive this message:
Copy this code, go to your application and paste it there:
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Where do I enter the code?

**Comment by tokland** [comment]
> Where do I enter the code?

Always paste command and full output in your reports. When using in CLI mode, you see something like:

> Check this link in your browser: LINK
> Enter verification code:

You paste the code there and press ENTER.

**Comment by LuckyMallari** [comment]
Does this have to be done Everytime? Using this w octoprint. And seems tokens expire..

**Comment by tokland** [comment]
> Does this have to be done Everytime?

No, it should ask only the first time. Then the credentials are saved.

**Comment by blacchollywood** [comment]
hey @tokland when i try to delete my (location $HOME/.youtube-upload-credentials.json) in order to create another credentials file, there seems to be none. how is this file really called and how can I find it?

**Comment by tokland** [comment]
You are looking at the right place. The code is: `default_credentials = os.path.join(home, ".youtube-upload-credentials.json")`

Are you sure you have already authenticated? if you try to upload a video it works without asking nothing?

To make sure the file is not somewhere else: `$ sudo updatedb && locate .youtube-upload-credentials.json`.

**Comment by blacchollywood** [comment]
Thanks I got it! Was a hidden file :)

**Comment by tokland** [comment]
Yes, that's how Unix filesystems work :)

**Comment by remorses** [comment]
Who generates this credentials file? Is it created automatically by google apis? I don't see anywhere in your code where you create it

**Comment by tokland** [comment]
.youtube-upload-credentials.json is created by the script. Check:

https://github.com/tokland/youtube-upload/blob/master/youtube_upload/main.py#L161
https://github.com/tokland/youtube-upload/blob/master/youtube_upload/auth/__init__.py#L38

**Comment by wangsunwuji** [comment]
My computer is a windows system, I did not find this file, how is it created?

**Comment by wangsunwuji** [comment]
When I uploaded it, it said that this file is missing.

**Comment by 20083017** [comment]
> > Where do I enter the code?
> 
> Always paste command and full output in your reports. When using in CLI mode, you see something like:
> 
> > Check this link in your browser: LINK
> > Enter verification code:
> 
> You paste the code there and press ENTER.

Hello,I'm getting there on Windows, But when I pressed Enter, I got this error!

```
Traceback (most recent call last):
  File "E:\game\youtube-upload\bin\youtube-upload", line 10, in <module>
    main.run()
  File "E:\game\youtube-upload\bin\..\youtube_upload\main.py", line 290, in run
    sys.exit(lib.catch_exceptions(EXIT_CODES, main, sys.argv[1:]))
  File "E:\game\youtube-upload\bin\..\youtube_upload\lib.py", line 44, in catch_exceptions
    fun(*args, **kwargs)
  File "E:\game\youtube-upload\bin\..\youtube_upload\main.py", line 283, in main
    run_main(parser, options, args)
  File "E:\game\youtube-upload\bin\..\youtube_upload\main.py", line 196, in run_main
    youtube = get_youtube_handler(options)
  File "E:\game\youtube-upload\bin\..\youtube_upload\main.py", line 179, in get_youtube_handler
    return auth.get_resource(client_secrets, credentials,
  File "E:\game\youtube-upload\bin\..\youtube_upload\auth\__init__.py", line 41, in get_resource
    credentials = _get_credentials(flow, storage, get_code_callback)
  File "E:\game\youtube-upload\bin\..\youtube_upload\auth\__init__.py", line 33, in _get_credentials
    return _get_credentials_interactively(flow, storage, get_code_callback)
  File "E:\game\youtube-upload\bin\..\youtube_upload\auth\__init__.py", line 21, in _get_credentials_interactively
    credential = flow.step2_exchange(code, http=None)
  File "D:\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "D:\lib\site-packages\oauth2client\client.py", line 2053, in step2_exchange
    resp, content = transport.request(
  File "D:\lib\site-packages\oauth2client\transport.py", line 280, in request
    return http_callable(uri, method=method, body=body, headers=headers,
  File "D:\lib\site-packages\httplib2\__init__.py", line 1708, in request
    (response, content) = self._request(
  File "D:\lib\site-packages\httplib2\__init__.py", line 1424, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "D:\lib\site-packages\httplib2\__init__.py", line 1346, in _conn_request
    conn.connect()
  File "D:\lib\site-packages\httplib2\__init__.py", line 1182, in connect
    raise socket_err
  File "D:\lib\site-packages\httplib2\__init__.py", line 1136, in connect
    sock.connect((self.host, self.port))
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
```
