### ISSUE TITLE
Youtube is bottlenecking upload?

### ISSUE THREAD

**Issue by baltasvejas** [tokland/youtube-upload#78]
I was using youtube-upload for around two years probably.
Now I started experiencing symptoms as if youtube is not allowing to upload the file.
During last two weeks I get upload behaviour as below:

    me@ubuntu:/srv/myproject$ ifstat -b
           eth0
     Kbps in  Kbps out
      143.19   8202.85
       27.81    398.59
        0.52      1.05
      184.94   9807.61
      402.90  16431.09
      438.10  21328.99
      110.51   4336.48
        0.52      1.05
      186.33   8600.05
        0.52      1.05
        0.52      1.05
      308.36  14289.46
      243.64  11604.66
        0.52      1.05
        0.52      1.05
        0.52      1.05
        0.52      1.05
        0.52      1.05
        0.98      1.05
        0.52      1.05

Finally I get error like:

    [RequestError] Server response was: generic::deadline_exceeded: file operation deadline expired 126.261us ago

I tried this with different accounts and got same result.
I also reinstalled youtube-upload so it is latest version. Nothing changed.

I think my command has no problem as it worked previously ok:

    me@ubuntu:/srv/myproject$ youtube-upload --title='My_test_video' --privacy='unlisted' --client-secrets='/srv/myproject/youtube-secret.json' --credentials-file='/srv/myproject/youtube-credentials.json' --category='Education' --description='My test description' --tags='python, youtube' My_test_video.mp4
    Using client secrets: /srv/myproject/youtube-secret.json
    Using credentials file: /srv/myproject/youtube-credentials.json
    Using category: Education (id=27)
    Start upload: My_test_video.mp4
      0% |                                               | ETA:  18:26:33 235.49 kB/s

Any suggestion?

**Comment by asperduti** [comment]
I recently started to use the last version and i do not have any problem. I was using the old version with email authentication but since the two days ago is deprecated.
Did you try with the the default app(the client secret file default) or a new one?

**Comment by baltasvejas** [comment]
Just tried without providing client secret file (default client secret), however same.
I thought my authentication token expired so I tried with new password previously already.

**Comment by tokland** [comment]
Sorry, I have no idea, I have never seen this error nor google shows any helpful info about it.
