### ISSUE TITLE
Running under wins

### ISSUE THREAD

**Issue by chudn** [tokland/youtube-upload#80]
How do I run this version of youtube-upload under wins? In previous version i ran youtube_upload/youtube_upload.py "arguments", but in this one u cannot find a solution.

**Comment by chudn** [comment]
Found it. If someone needs it... just create .bat file next to python.exe, and put following into .bat file:
youtube-upload-master\bin\youtube-upload --title="A.S. Mutter" path/to/file

youtube-upload-master\bin\youtube-upload must be a relative path in this case.

**Comment by tokland** [comment]
Glad it worked.
