### ISSUE TITLE
upload multiple videoes

### ISSUE THREAD

**Issue by mykeylynx** [tokland/youtube-upload#82]
Anyone know if its possible to upload videos consecutively?

**Comment by tokland** [comment]
The script uploads only a single video, to upload different videos you use the shell scripting language you have available in your OS (Bash, Windows PowerShell, etc).

**Comment by mykeylynx** [comment]
Thank you, and Idea of what the script would look like?


IT Management
. . . . . . . . . . . . . . . . . . . . .
*Michael Dweck*
646-418-3595
michael@savvysavant.com
Skype: Michael_Dweck
www.linkedin.com/in/michaeldweck

**Comment by ManuCart** [comment]
Hi,
This is my very simple script
https://github.com/ManuCart/ServicePi/blob/master/service/youtube-upload
