### ISSUE TITLE
cron problem

### ISSUE THREAD

**Issue by miguelniserias** [tokland/youtube-upload#83]
Hi, I have a script, it works perfectly if I run it manually, but not when I use cron. Do you know why is happening this? I have tried to do another job with this script and it worked perfectly. The problem is in youtube-upload.

////////////timelapse.sh
fechaAyer=$(date --date='-1 day' +"%d/%m/%y")

echo "subiendo a youtube..."
youtube-upload --title="Timelapse $fechaAyer" /root/timelapse/temp2/timelapse.avi > /root/timelapse/temp2/url.txt

/////////////crontab
03 19 * * * /root/timelapse/timelapse.sh

**Comment by tokland** [comment]
This goes out of the scope of the project. You may try in superuser.com or similar. You'll need to provide some log error, otherwise nobody will know what's going on. With cron usually the problem is the path, the executables are not found. Use full paths.
