### ISSUE TITLE
Rate limiting ? (Not a bug, removed feature?)

### ISSUE THREAD

**Issue by Nihim** [tokland/youtube-upload#86]
It might be a feature that was removed and just found it from the old google page: https://code.google.com/p/youtube-upload/wiki/Readme

where it states to throttle the upload speed to use an extra bash script - Upload videos with curl

`youtube-upload --get-upload-form-info [OPTIONS] | bash examples/upload_with_curl.sh --limit-rate 100k`

from what I 've seen "--get-upload-form-info" no longer exists and generally it doesn't seem to affect the upload speed (no errors from youtube-upload or the bash script - permissions are ok).

Is there an alternative way? Anyone has it working? Or should I just forget about it.

Cheers

**Comment by tokland** [comment]
https://developers.google.com/youtube/v3/docs/videos/insert#http-request

I guess it's still possible but I have not find documentation. I won't tacke this, but pull requests welcome.

**Comment by porjo** [comment]
@Nihim shameless plug - my uploader supports ratelimiting
https://github.com/porjo/youtubeuploader

**Comment by tokland** [comment]
@porjo Cool, added to section "Alternatives"

https://github.com/tokland/youtube-upload/blob/master/README.md
