### ISSUE TITLE
Prebuilt packages

### ISSUE THREAD

**Issue by qiuwei** [tokland/youtube-upload#89]
Hi,
Thanks for the awesome work.

 I've made some packages for mac, debian and redhat.

https://github.com/qiuwei/youtube-upload/releases

This might make the installation more convenient for the users.

**Comment by tokland** [comment]
thx!

@zachwhalen: could you test the Mac release?

**Comment by qiuwei** [comment]
Sorry it was a mistake. I built it from the downloaded master.zip

**Comment by tokland** [comment]
Added to the README, thx @qiuwei!
