### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by josbrouwer** [tokland/youtube-upload#91]
Hi,

i want to installing the script on a new osx machine but i'm getting this error.

lvbjumbo:youtube-upload-master admin$ /usr/local/bin/youtube-upload --credentials-file _TOKENJelmerHoekstra --title="test_Upload-Review" --description="test" --tags="test" --privacy="unlisted" /Users/admin/Desktop/Test.MOV
Traceback (most recent call last):
  File "/usr/local/bin/youtube-upload", line 9, in <module>
    from youtube_upload import main    
ImportError: No module named youtube_upload

i have got the same setup as my old machine, it is working there, where did i go wrong ;(
any ideas?

Regards Jos

**Comment by josbrouwer** [comment]
i've solved the issue by following the steps on this website: https://wolfpaulus.com/journal/mac/installing_python_osx/

Regards Jos

**Comment by tokland** [comment]
Great, closing then.
