### ISSUE TITLE
How to use --location parameter

### ISSUE THREAD

**Issue by lasdou** [tokland/youtube-upload#93]
Hello,

thanks for this usefull tool.

I want to use the --location parameter but i don't understand how to use it, the example is not clear.

Could you please add a more comprehensive example ?

Thank you very much.

Best Regards

**Comment by tokland** [comment]
The option is: ```--location=latitude=VAL,longitude=VAL[,altitude=VAL]```
An example of my town: ```--location="latitude=41.55,longitude=2.2167"```
