### ISSUE TITLE
How to send multiline description

### ISSUE THREAD

**Issue by lasdou** [tokland/youtube-upload#94]
Hi, 

it's me again, i need to know how to send a multiline description. I have try with a line feed but it doesn't work.The final description in youtube appears in one unique line.

Can you give an example of command line usage with multiline description please ?

Thank you very much

**Comment by tokland** [comment]
It depends on the OS you are using. I can only help for UNIX (Mac and Linux).

**Comment by lasdou** [comment]
I'm on debian linux

**Comment by tokland** [comment]
Then it's easy:  ```-description="$(< description.txt)"```

**Comment by lasdou** [comment]
Thank you for the response, but i got an error.

Here is the commande line : 

> youtube-upload --title="My title" --description="$(< /home/pi/description.txt)" --category="Science & Technology" --tags="science" --recording-date="2016-01-06T16:03:48.0Z" --publish-at="2016-01-06T16:03:48.0Z" --default-language="fr" --default-audio-language="fr" --client-secrets=/home/pi/client_secrets_youtube_uploader.json /home/pi/cron_scripts/file.flv

Here is the console output : 

> Using client secrets: /home/pi/client_secrets_youtube_uploader.json
> Using credentials file: /home/pi/.youtube-upload-credentials.json
> Your video will remain private until specified date.
> Using category: Science & Technology (id=28)
> Start upload: /home/pi/cron_scripts/file.flv
> [RequestError] Server response: Failed to parse Content-Range header.

**Comment by lasdou** [comment]
Finally it is working with line feed direcly in the command line like that : 

> youtube-upload --title="My title" --description="Line 1
> Line2
> Line3" --category="Science & Technology" --tags="science" --recording-date="2016-01-06T16:03:48.0Z" --publish-at="2016-01-06T16:03:48.0Z" --default-language="fr" --default-audio-language="fr" --client-secrets=/home/pi/client_secrets_youtube_uploader.json /home/pi/cron_scripts/file.flv

Thanks for your help.
