### ISSUE TITLE
Wrong return codes and error descriptions

### ISSUE THREAD

**Issue by BakermanLP** [tokland/youtube-upload#98]
Hello there,

that's only a minor problem, but I wanted to report it. When I upload a video and a error code will be returned, the wrong error code is shown at the end. Here is a example:

`[RequestError] Server response: b'{\n "error": {\n  "errors": [\n   {\n    "domain": "youtube.video",\n    "reason": "invalidTags",\n    "message": "The request metadata specifies invalid video keywords.",\n    "locationType": "other",\n    "location": "body.snippet.tags"\n   }\n  ],\n  "code": 400,\n  "message": "The request metadata specifies invalid video keywords."\n }\n}'
Upload Returns: 3
Bereits hochgeladen\n
`

I don't know, if that can be fixed.

Thanks a lot for this tool

Michael (aka BakermanLP)

**Comment by tokland** [comment]
ede01c24 should fix it. thx.
